/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms.Manager;

import forms.Login.frmLogin;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.logging.log4j.LogManager;

/**
 *
 * @author wills
 */
public class frmManagerEndUserRegistration extends javax.swing.JFrame {

    /**
     * Creates new form frmManagerEndUserRegistration
     */
    
    private String manager_id;
    private String manager_name;
    private String manager_pass;
    private String manager_role;
    
    private static final org.apache.logging.log4j.Logger logger = LogManager.getLogger(frmManagerEndUserRegistration.class);
    
    public frmManagerEndUserRegistration() {
        initComponents();
        this.manager_id = "";
        this.manager_name = "";
        this.manager_pass = "";
        this.manager_role = "";
        cmbRegisterUserRole.setSelectedIndex(-1);
    }
    
    public frmManagerEndUserRegistration(String id, String name, String pass, String role) {
        initComponents();
        this.manager_id = id;
        this.manager_name = name;
        this.manager_pass = pass;
        this.manager_role = role;
        cmbRegisterUserRole.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlEndUserRegistrationBackground = new javax.swing.JPanel();
        pnlInnerRegistrationBackground = new javax.swing.JPanel();
        lblRegisterTitle = new java.awt.Label();
        lblRegisterUsernameTitle = new javax.swing.JLabel();
        lblRegisterPasswordTitle = new javax.swing.JLabel();
        lblRegisterConfirmPasswordTitle = new javax.swing.JLabel();
        txtRegisterUsername = new javax.swing.JTextField();
        lblRegisterDescription = new javax.swing.JLabel();
        btnCancelRegister = new javax.swing.JButton();
        btnRegisterUserAccount = new javax.swing.JButton();
        txtRegisterPassword = new javax.swing.JPasswordField();
        txtRegisterConfirmPassword = new javax.swing.JPasswordField();
        lblRegisterUserRoleTitle = new javax.swing.JLabel();
        cmbRegisterUserRole = new javax.swing.JComboBox<>();
        btnBackEndUserRegistration = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("End User Registration");
        setBackground(new java.awt.Color(51, 51, 51));
        setResizable(false);

        pnlEndUserRegistrationBackground.setBackground(new java.awt.Color(51, 51, 51));
        pnlEndUserRegistrationBackground.setPreferredSize(new java.awt.Dimension(1230, 700));
        pnlEndUserRegistrationBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlInnerRegistrationBackground.setBackground(new java.awt.Color(71, 71, 71));

        lblRegisterTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblRegisterTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblRegisterTitle.setText("Register an Account");

        lblRegisterUsernameTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblRegisterUsernameTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblRegisterUsernameTitle.setText("USERNAME");

        lblRegisterPasswordTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblRegisterPasswordTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblRegisterPasswordTitle.setText("PASSWORD");

        lblRegisterConfirmPasswordTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblRegisterConfirmPasswordTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblRegisterConfirmPasswordTitle.setText("CONFIRM PASSWORD");

        txtRegisterUsername.setBackground(new java.awt.Color(51, 51, 51));
        txtRegisterUsername.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        txtRegisterUsername.setForeground(new java.awt.Color(255, 255, 255));
        txtRegisterUsername.setBorder(null);

        lblRegisterDescription.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblRegisterDescription.setForeground(new java.awt.Color(255, 255, 255));
        lblRegisterDescription.setText("Create a username and a password and pick a role");
        lblRegisterDescription.setToolTipText("");

        btnCancelRegister.setBackground(new java.awt.Color(102, 102, 102));
        btnCancelRegister.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnCancelRegister.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelRegister.setText("CANCEL");
        btnCancelRegister.setToolTipText("");
        btnCancelRegister.setBorder(null);
        btnCancelRegister.setBorderPainted(false);
        btnCancelRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelRegister.setDefaultCapable(false);
        btnCancelRegister.setName(""); // NOI18N
        btnCancelRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelRegisterActionPerformed(evt);
            }
        });

        btnRegisterUserAccount.setBackground(new java.awt.Color(102, 0, 248));
        btnRegisterUserAccount.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnRegisterUserAccount.setForeground(new java.awt.Color(255, 255, 255));
        btnRegisterUserAccount.setText("REGISTER");
        btnRegisterUserAccount.setToolTipText("");
        btnRegisterUserAccount.setBorder(null);
        btnRegisterUserAccount.setBorderPainted(false);
        btnRegisterUserAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegisterUserAccount.setDefaultCapable(false);
        btnRegisterUserAccount.setName(""); // NOI18N
        btnRegisterUserAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterUserAccountActionPerformed(evt);
            }
        });

        txtRegisterPassword.setBackground(new java.awt.Color(51, 51, 51));
        txtRegisterPassword.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        txtRegisterPassword.setForeground(new java.awt.Color(255, 255, 255));

        txtRegisterConfirmPassword.setBackground(new java.awt.Color(51, 51, 51));
        txtRegisterConfirmPassword.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        txtRegisterConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));

        lblRegisterUserRoleTitle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblRegisterUserRoleTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblRegisterUserRoleTitle.setText("User Role");

        cmbRegisterUserRole.setBackground(new java.awt.Color(51, 51, 51));
        cmbRegisterUserRole.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cmbRegisterUserRole.setForeground(new java.awt.Color(255, 255, 255));
        cmbRegisterUserRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Customer" }));

        javax.swing.GroupLayout pnlInnerRegistrationBackgroundLayout = new javax.swing.GroupLayout(pnlInnerRegistrationBackground);
        pnlInnerRegistrationBackground.setLayout(pnlInnerRegistrationBackgroundLayout);
        pnlInnerRegistrationBackgroundLayout.setHorizontalGroup(
            pnlInnerRegistrationBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInnerRegistrationBackgroundLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(pnlInnerRegistrationBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInnerRegistrationBackgroundLayout.createSequentialGroup()
                        .addComponent(lblRegisterDescription)
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInnerRegistrationBackgroundLayout.createSequentialGroup()
                        .addGroup(pnlInnerRegistrationBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRegisterUserRoleTitle)
                            .addGroup(pnlInnerRegistrationBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtRegisterUsername, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                                .addComponent(lblRegisterConfirmPasswordTitle)
                                .addComponent(lblRegisterPasswordTitle)
                                .addComponent(lblRegisterUsernameTitle)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInnerRegistrationBackgroundLayout.createSequentialGroup()
                                    .addComponent(btnRegisterUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnCancelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtRegisterPassword)
                                .addComponent(txtRegisterConfirmPassword))
                            .addComponent(cmbRegisterUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInnerRegistrationBackgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lblRegisterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        pnlInnerRegistrationBackgroundLayout.setVerticalGroup(
            pnlInnerRegistrationBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInnerRegistrationBackgroundLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lblRegisterTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(lblRegisterDescription)
                .addGap(18, 18, 18)
                .addComponent(lblRegisterUsernameTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRegisterUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegisterPasswordTitle)
                .addGap(11, 11, 11)
                .addComponent(txtRegisterPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(lblRegisterConfirmPasswordTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRegisterConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblRegisterUserRoleTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbRegisterUserRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(pnlInnerRegistrationBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegisterUserAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38))
        );

        pnlEndUserRegistrationBackground.add(pnlInnerRegistrationBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(409, 76, -1, -1));

        btnBackEndUserRegistration.setBackground(new java.awt.Color(102, 102, 102));
        btnBackEndUserRegistration.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnBackEndUserRegistration.setForeground(new java.awt.Color(255, 255, 255));
        btnBackEndUserRegistration.setText("BACK");
        btnBackEndUserRegistration.setToolTipText("");
        btnBackEndUserRegistration.setBorder(null);
        btnBackEndUserRegistration.setBorderPainted(false);
        btnBackEndUserRegistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackEndUserRegistration.setDefaultCapable(false);
        btnBackEndUserRegistration.setName(""); // NOI18N
        btnBackEndUserRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackEndUserRegistrationActionPerformed(evt);
            }
        });
        pnlEndUserRegistrationBackground.add(btnBackEndUserRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(1098, 631, 102, 37));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEndUserRegistrationBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEndUserRegistrationBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnlEndUserRegistrationBackground.getAccessibleContext().setAccessibleName("End User Registration");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterUserAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterUserAccountActionPerformed
        try {
            RegisterUser();
        } catch(Exception e){
            Logger.getLogger(frmManagerEndUserRegistration.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnRegisterUserAccountActionPerformed

    private void btnCancelRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelRegisterActionPerformed
        logger.info(manager_role + ": " + manager_name + " " + "Cancelled User Registration");
        txtRegisterUsername.setText(null);
        txtRegisterPassword.setText(null);
        txtRegisterConfirmPassword.setText(null);
    }//GEN-LAST:event_btnCancelRegisterActionPerformed

    private void btnBackEndUserRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackEndUserRegistrationActionPerformed
        this.dispose();
        frmManagerMainMenu frmMMM = new frmManagerMainMenu(manager_id, manager_name, manager_pass, manager_role);
        frmMMM.setVisible(true);
        logger.info(manager_role + ": " + manager_name + " " + "Quit User Registraiton back to Manager Main Menu");
    }//GEN-LAST:event_btnBackEndUserRegistrationActionPerformed

    public void RegisterUser(){
        String username = txtRegisterUsername.getText();
        String password = txtRegisterPassword.getText();
        String con_password = txtRegisterConfirmPassword.getText();
        
        int user_role_index = cmbRegisterUserRole.getSelectedIndex();
        
        if(username.equals("") || password.equals("") || con_password.equals("") || user_role_index == -1){
            JOptionPane.showMessageDialog(this, "Please fill up all the information!");
            logger.error(manager_role + ": " + manager_name + " " + "failed to Register a User (Missing Information)");
        }
        else if(!password.equals(con_password)){
            JOptionPane.showMessageDialog(this, "The confirmation password is incorrect!");
            logger.error(manager_role + ": " + manager_name + " " + "failed to Register a User (Confirmation Password Wrong)");
            txtRegisterConfirmPassword.setText(null);
        }
        else{
            String user_role = cmbRegisterUserRole.getSelectedItem().toString();
            User_Registration ur = new User_Registration(username, password, con_password, user_role);
            ur.saveInformation();
            
            logger.info(manager_role + ": " + manager_name + " " + "User Registration Successful, " + user_role + " " + username + " has been created");
            
            txtRegisterUsername.setText(null);
            txtRegisterPassword.setText(null);
            txtRegisterConfirmPassword.setText(null);
            cmbRegisterUserRole.setSelectedIndex(-1);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmManagerEndUserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmManagerEndUserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmManagerEndUserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmManagerEndUserRegistration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmManagerEndUserRegistration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackEndUserRegistration;
    private javax.swing.JButton btnCancelRegister;
    private javax.swing.JButton btnRegisterUserAccount;
    private javax.swing.JComboBox<String> cmbRegisterUserRole;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblRegisterConfirmPasswordTitle;
    private javax.swing.JLabel lblRegisterDescription;
    private javax.swing.JLabel lblRegisterPasswordTitle;
    private java.awt.Label lblRegisterTitle;
    private javax.swing.JLabel lblRegisterUserRoleTitle;
    private javax.swing.JLabel lblRegisterUsernameTitle;
    private javax.swing.JPanel pnlEndUserRegistrationBackground;
    private javax.swing.JPanel pnlInnerRegistrationBackground;
    private javax.swing.JPasswordField txtRegisterConfirmPassword;
    private javax.swing.JPasswordField txtRegisterPassword;
    private javax.swing.JTextField txtRegisterUsername;
    // End of variables declaration//GEN-END:variables
}
