/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms.Manager;

import forms.Login.frmLogin;
import java.io.File;
import java.io.FileNotFoundException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.apache.logging.log4j.LogManager;

/**
 *
 * @author User
 */
public class frmManagerSalesReport extends javax.swing.JFrame {

    /**
     * Creates new form frmCustMenuCategories
     */
    
    private String manager_id;
    private String manager_name;
    private String manager_pass;
    private String manager_role;
    
    private static final org.apache.logging.log4j.Logger logger = LogManager.getLogger(frmManagerSalesReport.class);
    
    Date defaultDate = new Date();
    
    public frmManagerSalesReport() {
        initComponents();

        datechSalesReportSelectPeriodStart.setDate(defaultDate);
        datechSalesReportSelectPeriodEnd.setDate(defaultDate);
        fileToSalesReportTable();
        addCategorytocombobox();
        cmbSalesReportCategory.setSelectedIndex(-1);
        mostSold();
        leastSold();
    }
    
    public frmManagerSalesReport(String id, String name, String pass, String role) {
        initComponents();
        this.manager_id = id;
        this.manager_name = name;
        this.manager_pass = pass;
        this.manager_role = role;

        datechSalesReportSelectPeriodStart.setDate(defaultDate);
        datechSalesReportSelectPeriodEnd.setDate(defaultDate);
        fileToSalesReportTable();
        addCategorytocombobox();
        cmbSalesReportCategory.setSelectedIndex(-1);
        mostSold();
        leastSold();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSalesReportBackground = new javax.swing.JPanel();
        lblSalesReportTitle = new javax.swing.JLabel();
        btnSalesReportBack = new javax.swing.JButton();
        pnlInnerSalesReportBackground = new javax.swing.JPanel();
        lblSalesReportTableTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSalesReport = new javax.swing.JTable();
        lblSalesReportSelectPeriodEnd = new javax.swing.JLabel();
        lblSalesReportLeastSoldItemCategory = new javax.swing.JLabel();
        lblSalesReportCategoryAmountEarnedTitle = new javax.swing.JLabel();
        datechSalesReportSelectPeriodEnd = new com.toedter.calendar.JDateChooser();
        datechSalesReportSelectPeriodStart = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        btnSetSalesReportSelectPeriod = new javax.swing.JButton();
        btnClearSalesReportSelectPeriod = new javax.swing.JButton();
        lblSalesReportMostSoldItem = new javax.swing.JLabel();
        lblSalesReportMostSoldTitle = new javax.swing.JLabel();
        lblSalesReportTotalEarningsTitle = new javax.swing.JLabel();
        lblSalesReportTotalEarningsRM = new javax.swing.JLabel();
        lblSalesReportTotalEarningsAmount = new javax.swing.JLabel();
        lblSalesReportLeastSoldTitle = new javax.swing.JLabel();
        lblSalesReportLeastSoldItem = new javax.swing.JLabel();
        lblSalesReportLeastSoldItemQuantity = new javax.swing.JLabel();
        lblSalesReportMostSoldItemQuantity = new javax.swing.JLabel();
        lblSalesReportMostSoldItemCategory = new javax.swing.JLabel();
        lblSalesReportSelectPeriod = new javax.swing.JLabel();
        cmbSalesReportCategory = new javax.swing.JComboBox<>();
        lblSalesReportCategoryTitle = new javax.swing.JLabel();
        lblSalesReportSelectPeriodStart = new javax.swing.JLabel();
        lblSalesReportCategoryAmountEarnedAmount = new javax.swing.JLabel();
        lblSalesReportCategoryAmountEarnedRM = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales Report");
        setBackground(new java.awt.Color(51, 51, 51));
        setName("frmCustMenuCategories"); // NOI18N
        setResizable(false);

        pnlSalesReportBackground.setBackground(new java.awt.Color(51, 51, 51));
        pnlSalesReportBackground.setName("frmCustMenuCategories"); // NOI18N
        pnlSalesReportBackground.setPreferredSize(new java.awt.Dimension(1230, 700));
        pnlSalesReportBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSalesReportTitle.setBackground(new java.awt.Color(71, 71, 71));
        lblSalesReportTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblSalesReportTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSalesReportTitle.setText("Sales Report");
        pnlSalesReportBackground.add(lblSalesReportTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 606, 53));

        btnSalesReportBack.setBackground(new java.awt.Color(102, 102, 102));
        btnSalesReportBack.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnSalesReportBack.setForeground(new java.awt.Color(255, 255, 255));
        btnSalesReportBack.setText("BACK");
        btnSalesReportBack.setToolTipText("");
        btnSalesReportBack.setBorder(null);
        btnSalesReportBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalesReportBack.setDefaultCapable(false);
        btnSalesReportBack.setName(""); // NOI18N
        btnSalesReportBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalesReportBackActionPerformed(evt);
            }
        });
        pnlSalesReportBackground.add(btnSalesReportBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 192, 45));

        pnlInnerSalesReportBackground.setBackground(new java.awt.Color(71, 71, 71));
        pnlInnerSalesReportBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSalesReportTableTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSalesReportTableTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSalesReportTableTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSalesReportTableTitle.setText("Sales Report");
        pnlInnerSalesReportBackground.add(lblSalesReportTableTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 200, 40));

        tblSalesReport.setAutoCreateRowSorter(true);
        tblSalesReport.setBackground(new java.awt.Color(71, 71, 71));
        tblSalesReport.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblSalesReport.setForeground(new java.awt.Color(255, 255, 255));
        tblSalesReport.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Category", "Item", "Unit Price", "Quantity_Sold", "Amount_Earned"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSalesReport.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblSalesReport);
        if (tblSalesReport.getColumnModel().getColumnCount() > 0) {
            tblSalesReport.getColumnModel().getColumn(0).setMaxWidth(30);
            tblSalesReport.getColumnModel().getColumn(1).setMaxWidth(100);
            tblSalesReport.getColumnModel().getColumn(2).setMaxWidth(200);
            tblSalesReport.getColumnModel().getColumn(3).setMaxWidth(100);
            tblSalesReport.getColumnModel().getColumn(4).setMaxWidth(100);
            tblSalesReport.getColumnModel().getColumn(5).setMaxWidth(100);
        }

        pnlInnerSalesReportBackground.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 630, 190));

        lblSalesReportSelectPeriodEnd.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSalesReportSelectPeriodEnd.setForeground(new java.awt.Color(255, 255, 255));
        lblSalesReportSelectPeriodEnd.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSalesReportSelectPeriodEnd.setText("End");
        lblSalesReportSelectPeriodEnd.setToolTipText("");
        pnlInnerSalesReportBackground.add(lblSalesReportSelectPeriodEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 100, 20));

        lblSalesReportLeastSoldItemCategory.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSalesReportLeastSoldItemCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblSalesReportLeastSoldItemCategory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSalesReportLeastSoldItemCategory.setToolTipText("");
        lblSalesReportLeastSoldItemCategory.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Category", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlInnerSalesReportBackground.add(lblSalesReportLeastSoldItemCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 160, 40));

        lblSalesReportCategoryAmountEarnedTitle.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSalesReportCategoryAmountEarnedTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSalesReportCategoryAmountEarnedTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSalesReportCategoryAmountEarnedTitle.setText("Amount Earned");
        lblSalesReportCategoryAmountEarnedTitle.setToolTipText("");
        pnlInnerSalesReportBackground.add(lblSalesReportCategoryAmountEarnedTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 370, 130, 20));

        datechSalesReportSelectPeriodEnd.setDateFormatString("dd-MM-yyyy");
        pnlInnerSalesReportBackground.add(datechSalesReportSelectPeriodEnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 170, -1));

        datechSalesReportSelectPeriodStart.setDateFormatString("dd-MM-yyyy");
        pnlInnerSalesReportBackground.add(datechSalesReportSelectPeriodStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 170, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Menu List");
        pnlInnerSalesReportBackground.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, -180, 200, 40));

        btnSetSalesReportSelectPeriod.setBackground(new java.awt.Color(102, 0, 248));
        btnSetSalesReportSelectPeriod.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnSetSalesReportSelectPeriod.setForeground(new java.awt.Color(255, 255, 255));
        btnSetSalesReportSelectPeriod.setText("SET");
        btnSetSalesReportSelectPeriod.setToolTipText("");
        btnSetSalesReportSelectPeriod.setBorder(null);
        btnSetSalesReportSelectPeriod.setBorderPainted(false);
        btnSetSalesReportSelectPeriod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSetSalesReportSelectPeriod.setDefaultCapable(false);
        btnSetSalesReportSelectPeriod.setName(""); // NOI18N
        btnSetSalesReportSelectPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetSalesReportSelectPeriodActionPerformed(evt);
            }
        });
        pnlInnerSalesReportBackground.add(btnSetSalesReportSelectPeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 70, 37));

        btnClearSalesReportSelectPeriod.setBackground(new java.awt.Color(102, 102, 102));
        btnClearSalesReportSelectPeriod.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnClearSalesReportSelectPeriod.setForeground(new java.awt.Color(255, 255, 255));
        btnClearSalesReportSelectPeriod.setText("CLEAR");
        btnClearSalesReportSelectPeriod.setToolTipText("");
        btnClearSalesReportSelectPeriod.setBorder(null);
        btnClearSalesReportSelectPeriod.setBorderPainted(false);
        btnClearSalesReportSelectPeriod.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClearSalesReportSelectPeriod.setDefaultCapable(false);
        btnClearSalesReportSelectPeriod.setName(""); // NOI18N
        btnClearSalesReportSelectPeriod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearSalesReportSelectPeriodActionPerformed(evt);
            }
        });
        pnlInnerSalesReportBackground.add(btnClearSalesReportSelectPeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 70, 37));

        lblSalesReportMostSoldItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSalesReportMostSoldItem.setForeground(new java.awt.Color(255, 255, 255));
        lblSalesReportMostSoldItem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSalesReportMostSoldItem.setToolTipText("");
        lblSalesReportMostSoldItem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlInnerSalesReportBackground.add(lblSalesReportMostSoldItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 280, 330, 40));

        lblSalesReportMostSoldTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSalesReportMostSoldTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSalesReportMostSoldTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSalesReportMostSoldTitle.setText("Most Sold");
        lblSalesReportMostSoldTitle.setToolTipText("");
        pnlInnerSalesReportBackground.add(lblSalesReportMostSoldTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 280, 90, 40));

        lblSalesReportTotalEarningsTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSalesReportTotalEarningsTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSalesReportTotalEarningsTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSalesReportTotalEarningsTitle.setText("Total Earnings");
        lblSalesReportTotalEarningsTitle.setToolTipText("");
        pnlInnerSalesReportBackground.add(lblSalesReportTotalEarningsTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 280, 130, 40));

        lblSalesReportTotalEarningsRM.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSalesReportTotalEarningsRM.setForeground(new java.awt.Color(255, 255, 255));
        lblSalesReportTotalEarningsRM.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSalesReportTotalEarningsRM.setText("RM");
        lblSalesReportTotalEarningsRM.setToolTipText("");
        pnlInnerSalesReportBackground.add(lblSalesReportTotalEarningsRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 320, 30, 40));

        lblSalesReportTotalEarningsAmount.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSalesReportTotalEarningsAmount.setForeground(new java.awt.Color(255, 255, 255));
        lblSalesReportTotalEarningsAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalesReportTotalEarningsAmount.setToolTipText("");
        lblSalesReportTotalEarningsAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlInnerSalesReportBackground.add(lblSalesReportTotalEarningsAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 320, 120, 40));

        lblSalesReportLeastSoldTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSalesReportLeastSoldTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSalesReportLeastSoldTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSalesReportLeastSoldTitle.setText("Least Sold");
        lblSalesReportLeastSoldTitle.setToolTipText("");
        pnlInnerSalesReportBackground.add(lblSalesReportLeastSoldTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 90, 40));

        lblSalesReportLeastSoldItem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblSalesReportLeastSoldItem.setForeground(new java.awt.Color(255, 255, 255));
        lblSalesReportLeastSoldItem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSalesReportLeastSoldItem.setToolTipText("");
        lblSalesReportLeastSoldItem.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlInnerSalesReportBackground.add(lblSalesReportLeastSoldItem, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 380, 330, 40));

        lblSalesReportLeastSoldItemQuantity.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSalesReportLeastSoldItemQuantity.setForeground(new java.awt.Color(255, 255, 255));
        lblSalesReportLeastSoldItemQuantity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSalesReportLeastSoldItemQuantity.setToolTipText("");
        lblSalesReportLeastSoldItemQuantity.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QTY", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlInnerSalesReportBackground.add(lblSalesReportLeastSoldItemQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 430, 100, 40));

        lblSalesReportMostSoldItemQuantity.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSalesReportMostSoldItemQuantity.setForeground(new java.awt.Color(255, 255, 255));
        lblSalesReportMostSoldItemQuantity.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSalesReportMostSoldItemQuantity.setToolTipText("");
        lblSalesReportMostSoldItemQuantity.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "QTY", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlInnerSalesReportBackground.add(lblSalesReportMostSoldItemQuantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 100, 40));

        lblSalesReportMostSoldItemCategory.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSalesReportMostSoldItemCategory.setForeground(new java.awt.Color(255, 255, 255));
        lblSalesReportMostSoldItemCategory.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSalesReportMostSoldItemCategory.setToolTipText("");
        lblSalesReportMostSoldItemCategory.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Category", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlInnerSalesReportBackground.add(lblSalesReportMostSoldItemCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 330, 160, 40));

        lblSalesReportSelectPeriod.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSalesReportSelectPeriod.setForeground(new java.awt.Color(255, 255, 255));
        lblSalesReportSelectPeriod.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSalesReportSelectPeriod.setText("Select Period");
        lblSalesReportSelectPeriod.setToolTipText("");
        pnlInnerSalesReportBackground.add(lblSalesReportSelectPeriod, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 210, 40));

        cmbSalesReportCategory.setBackground(new java.awt.Color(51, 51, 51));
        cmbSalesReportCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmbSalesReportCategory.setForeground(new java.awt.Color(255, 255, 255));
        cmbSalesReportCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSalesReportCategoryActionPerformed(evt);
            }
        });
        pnlInnerSalesReportBackground.add(cmbSalesReportCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 330, 170, -1));

        lblSalesReportCategoryTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblSalesReportCategoryTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblSalesReportCategoryTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSalesReportCategoryTitle.setText("Category");
        lblSalesReportCategoryTitle.setToolTipText("");
        pnlInnerSalesReportBackground.add(lblSalesReportCategoryTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 210, 40));

        lblSalesReportSelectPeriodStart.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSalesReportSelectPeriodStart.setForeground(new java.awt.Color(255, 255, 255));
        lblSalesReportSelectPeriodStart.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSalesReportSelectPeriodStart.setText("Start");
        lblSalesReportSelectPeriodStart.setToolTipText("");
        pnlInnerSalesReportBackground.add(lblSalesReportSelectPeriodStart, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 100, 20));

        lblSalesReportCategoryAmountEarnedAmount.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSalesReportCategoryAmountEarnedAmount.setForeground(new java.awt.Color(255, 255, 255));
        lblSalesReportCategoryAmountEarnedAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalesReportCategoryAmountEarnedAmount.setToolTipText("");
        lblSalesReportCategoryAmountEarnedAmount.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlInnerSalesReportBackground.add(lblSalesReportCategoryAmountEarnedAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, 120, 40));

        lblSalesReportCategoryAmountEarnedRM.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSalesReportCategoryAmountEarnedRM.setForeground(new java.awt.Color(255, 255, 255));
        lblSalesReportCategoryAmountEarnedRM.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblSalesReportCategoryAmountEarnedRM.setText("RM");
        lblSalesReportCategoryAmountEarnedRM.setToolTipText("");
        pnlInnerSalesReportBackground.add(lblSalesReportCategoryAmountEarnedRM, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 30, 40));

        pnlSalesReportBackground.add(pnlInnerSalesReportBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 96, 990, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSalesReportBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlSalesReportBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleName("Sales Report");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSetSalesReportSelectPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetSalesReportSelectPeriodActionPerformed
        fileToSalesReportTable();
        cmbSalesReportCategory.setSelectedIndex(-1);
        mostSold();
        leastSold();
        sumAmountEarned();
        logger.info(manager_role + ": " + manager_name + " " + "Set Date Range for Sales Report");
    }//GEN-LAST:event_btnSetSalesReportSelectPeriodActionPerformed

    private void btnClearSalesReportSelectPeriodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearSalesReportSelectPeriodActionPerformed
        datechSalesReportSelectPeriodStart.setDate(defaultDate);
        datechSalesReportSelectPeriodEnd.setDate(defaultDate);
        fileToSalesReportTable();
        sumAmountEarned();
        logger.info(manager_role + ": " + manager_name + " " + "Cleared Set Date and Back to Default Date");
    }//GEN-LAST:event_btnClearSalesReportSelectPeriodActionPerformed

    private void cmbSalesReportCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSalesReportCategoryActionPerformed
        countCategoryAmountEarned();
        logger.info(manager_role + ": " + manager_name + " " + "Count sales of selected Category");
    }//GEN-LAST:event_cmbSalesReportCategoryActionPerformed

    private void btnSalesReportBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalesReportBackActionPerformed
        this.dispose();
        frmManagerMainMenu frmMMM = new frmManagerMainMenu(manager_id, manager_name, manager_pass, manager_role);
        frmMMM.setVisible(true);
        logger.info(manager_role + ": " + manager_name + " " + "Quit Sales Report back to Manager Main Menu");
    }//GEN-LAST:event_btnSalesReportBackActionPerformed

    public void fileToSalesReportTable(){
        File file = new File("D:\\Documents\\Uni_Modules\\Object Oriented Development with Java\\Group Assignment\\Group_9_APU_Cafeteria_Food_Ordering_System\\src\\main\\java\\Database\\food.txt");
        int foodID = 0;
        double foodPrice = 0;        
        String foodName = "";
        String foodCat = "";
        String foodDesc = "";
                
        try{
            Scanner scan = new Scanner(file);
            scan.useDelimiter("[|\n]");
            
            DefaultTableModel model = (DefaultTableModel) tblSalesReport.getModel();
            model.setRowCount(0);
            while(scan.hasNext()){
                foodID = Integer.parseInt(scan.next());
                foodCat = scan.next();
                foodName = scan.next();
                foodPrice = Double.parseDouble(scan.next());
                foodDesc = scan.next().trim();               
                int initial_qty = 0;
                model.addRow(new Object[] {foodID,foodCat,foodName,foodPrice,initial_qty});
            }    
            
            //count the quantity of each food sold
            File file2 = new File("D:\\Documents\\Uni_Modules\\Object Oriented Development with Java\\Group Assignment\\Group_9_APU_Cafeteria_Food_Ordering_System\\src\\main\\java\\Database\\order.txt");
            
            int orderfoodQtyIncrement = 0;
            for(int i=0; i<tblSalesReport.getRowCount(); i++){
                
                Scanner scan2 = new Scanner(file2);
                scan2.useDelimiter("[|\n]");
                
                while(scan2.hasNext()){
                    int orderID = Integer.parseInt(scan2.next());
                    int custID = Integer.parseInt(scan2.next());
                    String custUsnm = scan2.next();
                    String orderDatex = scan2.next();
                    String orderfoodName = scan2.next();
                    String orderfoodCat = scan2.next();
                    int orderfoodQty = Integer.parseInt(scan2.next());
                    double payAmt = Double.parseDouble(scan2.next());
                    String paymentDatex = scan2.next().trim();
                    Date paymentDate = new SimpleDateFormat("dd/MM/yyy").parse(paymentDatex);
                    
                    Date startDatex = datechSalesReportSelectPeriodStart.getDate();
                    String startDate = DateFormat.getDateInstance().format(startDatex);
                    Date endDatex = datechSalesReportSelectPeriodEnd.getDate();
                    String endDate = DateFormat.getDateInstance().format(endDatex);
                    
                    if((defaultDate.after(startDatex) && defaultDate.after(endDatex)) || (paymentDate.after(startDatex) && paymentDate.before(endDatex))){
                        if((model.getValueAt(i, 2).toString()).equals(orderfoodName)){
                        orderfoodQtyIncrement = Integer.parseInt(model.getValueAt(i, 4).toString());
                        orderfoodQty = orderfoodQty + orderfoodQtyIncrement;
                        model.setValueAt(orderfoodQty, i, 4);
                        }
                    }
                }
            }
            
            //Count total amount earned
            for(int i=0; i<tblSalesReport.getRowCount(); i++){
                double unit_price = Double.parseDouble(model.getValueAt(i, 3).toString());
                int quantity_sold = Integer.parseInt(model.getValueAt(i, 4).toString());
                
                double amount_earned = unit_price*quantity_sold;
                model.setValueAt(amount_earned, i, 5);
            }
            
        }catch (FileNotFoundException ex) {
            Logger.getLogger(frmManagerSalesReport.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(frmManagerSalesReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void addCategorytocombobox(){
         File category_file = new File("D:\\Documents\\Uni_Modules\\Object Oriented Development with Java\\Group Assignment\\Group_9_APU_Cafeteria_Food_Ordering_System\\src\\main\\java\\Database\\category.txt");

        try{
            Scanner scan = new Scanner(category_file);
            scan.useDelimiter("[|\n]");
            
            while(scan.hasNext()){
                int categoryid = Integer.parseInt(scan.next());
                String category = scan.next().trim();
                cmbSalesReportCategory.addItem(category);
            }
        } catch (Exception ex) {
            Logger.getLogger(frmManagerSalesReport.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void countCategoryAmountEarned(){
        if(cmbSalesReportCategory.getSelectedItem() != null){
            double cat_amount_earned = 0;
        
            DefaultTableModel model = (DefaultTableModel) tblSalesReport.getModel();

            for(int i=0; i<tblSalesReport.getRowCount(); i++){
                String catName = cmbSalesReportCategory.getSelectedItem().toString();
                double amount_earned = Double.parseDouble(model.getValueAt(i, 5).toString());

                if(catName.equals(model.getValueAt(i, 1).toString())){
                    cat_amount_earned = cat_amount_earned +  amount_earned;
                }
            }
            
            DecimalFormat df = new DecimalFormat("###.##");
            lblSalesReportCategoryAmountEarnedAmount.setText(df.format(cat_amount_earned));
        }
    }
    
    public void mostSold(){
        int max = 0;
        String output_item_name = "";
        String output_item_cat = "";
        
        for(int i=0; i<tblSalesReport.getRowCount(); i++){
            int val = Integer.parseInt(tblSalesReport.getValueAt(i, 4).toString());
            String item_name = tblSalesReport.getValueAt(i, 2).toString();
            String item_cat = tblSalesReport.getValueAt(i, 1).toString();
            
            if(val>max){
                max = val;
                output_item_name = item_name;
                output_item_cat = item_cat;
            }
        }
        lblSalesReportMostSoldItem.setText(output_item_name);
        lblSalesReportMostSoldItemCategory.setText(output_item_cat);
        lblSalesReportMostSoldItemQuantity.setText(Integer.toString(max));
    }
    
    public void leastSold(){
        int min = 0;
        String output_item_name = "";
        String output_item_cat = "";
        
        for(int i=0; i<tblSalesReport.getRowCount(); i++){
            String item_name = tblSalesReport.getValueAt(i, 2).toString();
            String item_cat = tblSalesReport.getValueAt(i, 1).toString();
            if(i == 0){
                min = Integer.parseInt(tblSalesReport.getValueAt(i, 4).toString());
                output_item_name = item_name;
                output_item_cat = item_cat;
            }else{
                int val = Integer.parseInt(tblSalesReport.getValueAt(i, 4).toString());
                
                if(min>val){
                    min = val;
                    output_item_name = item_name;
                    output_item_cat = item_cat;
                }
            }
        }
        lblSalesReportLeastSoldItem.setText(output_item_name);
        lblSalesReportLeastSoldItemCategory.setText(output_item_cat);
        lblSalesReportLeastSoldItemQuantity.setText(Integer.toString(min));
    }
    
    public void sumAmountEarned(){
        int rowsCount = tblSalesReport.getRowCount();
        double sum = 0;
        
        for(int i=0; i<rowsCount; i++){
            sum = sum + Double.parseDouble(tblSalesReport.getValueAt(i,5).toString());
        }
        DecimalFormat df = new DecimalFormat("###.##");
        lblSalesReportTotalEarningsAmount.setText(df.format(sum));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmManagerSalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmManagerSalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmManagerSalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmManagerSalesReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmManagerSalesReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClearSalesReportSelectPeriod;
    private javax.swing.JButton btnSalesReportBack;
    private javax.swing.JButton btnSetSalesReportSelectPeriod;
    private javax.swing.JComboBox<String> cmbSalesReportCategory;
    public static com.toedter.calendar.JDateChooser datechSalesReportSelectPeriodEnd;
    public static com.toedter.calendar.JDateChooser datechSalesReportSelectPeriodStart;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSalesReportCategoryAmountEarnedAmount;
    private javax.swing.JLabel lblSalesReportCategoryAmountEarnedRM;
    private javax.swing.JLabel lblSalesReportCategoryAmountEarnedTitle;
    private javax.swing.JLabel lblSalesReportCategoryTitle;
    private javax.swing.JLabel lblSalesReportLeastSoldItem;
    private javax.swing.JLabel lblSalesReportLeastSoldItemCategory;
    private javax.swing.JLabel lblSalesReportLeastSoldItemQuantity;
    private javax.swing.JLabel lblSalesReportLeastSoldTitle;
    private javax.swing.JLabel lblSalesReportMostSoldItem;
    private javax.swing.JLabel lblSalesReportMostSoldItemCategory;
    private javax.swing.JLabel lblSalesReportMostSoldItemQuantity;
    private javax.swing.JLabel lblSalesReportMostSoldTitle;
    private javax.swing.JLabel lblSalesReportSelectPeriod;
    private javax.swing.JLabel lblSalesReportSelectPeriodEnd;
    private javax.swing.JLabel lblSalesReportSelectPeriodStart;
    private javax.swing.JLabel lblSalesReportTableTitle;
    private javax.swing.JLabel lblSalesReportTitle;
    private javax.swing.JLabel lblSalesReportTotalEarningsAmount;
    private javax.swing.JLabel lblSalesReportTotalEarningsRM;
    private javax.swing.JLabel lblSalesReportTotalEarningsTitle;
    private javax.swing.JPanel pnlInnerSalesReportBackground;
    private javax.swing.JPanel pnlSalesReportBackground;
    public static javax.swing.JTable tblSalesReport;
    // End of variables declaration//GEN-END:variables
}
