/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms.Manager;

import forms.Login.frmLogin;
import org.apache.logging.log4j.LogManager;

/**
 *
 * @author Teoh Will Shen
 */
public class frmManagerMainMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmManagerMainMenu
     */
    
    private String manager_id;
    private String manager_name;
    private String manager_pass;
    private String manager_role;
    
    private static final org.apache.logging.log4j.Logger logger = LogManager.getLogger(frmManagerMainMenu.class);
    
    public frmManagerMainMenu() {
        initComponents();
    }
    
    public frmManagerMainMenu(String id, String name, String pass, String role){
            initComponents();
            this.manager_id = id;
            this.manager_name = name;
            this.manager_pass = pass;
            this.manager_role = role;
            lblManagerMainMenuName.setText(manager_name);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMainMenuBackground = new javax.swing.JPanel();
        pnlMalayFood = new javax.swing.JPanel();
        btnManagerMainMenuViewLogActivity = new javax.swing.JButton();
        pnlWesternFood2 = new javax.swing.JPanel();
        btnManagerMainMenuLogOut = new javax.swing.JButton();
        btnManagerMainMenuEndUserRegistration = new javax.swing.JButton();
        btnManagerMainMenuUpdateMenu = new javax.swing.JButton();
        btnManagerMainMenuUpdateMenuCategory = new javax.swing.JButton();
        btnManagerMainMenuViewSalesReport = new javax.swing.JButton();
        btnManagerMainMenuViewFeedback = new javax.swing.JButton();
        lblManagerMainMenuWelcomeTitle = new javax.swing.JLabel();
        lblManagerMainMenuName = new javax.swing.JLabel();
        btnManagerMainMenuViewUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manager Main Menu");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMainMenuBackground.setBackground(new java.awt.Color(51, 51, 51));
        pnlMainMenuBackground.setToolTipText("");
        pnlMainMenuBackground.setMaximumSize(new java.awt.Dimension(450, 700));
        pnlMainMenuBackground.setMinimumSize(new java.awt.Dimension(450, 700));
        pnlMainMenuBackground.setPreferredSize(new java.awt.Dimension(450, 700));
        pnlMainMenuBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMalayFood.setBackground(new java.awt.Color(71, 71, 71));

        javax.swing.GroupLayout pnlMalayFoodLayout = new javax.swing.GroupLayout(pnlMalayFood);
        pnlMalayFood.setLayout(pnlMalayFoodLayout);
        pnlMalayFoodLayout.setHorizontalGroup(
            pnlMalayFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        pnlMalayFoodLayout.setVerticalGroup(
            pnlMalayFoodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlMainMenuBackground.add(pnlMalayFood, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 99, -1, -1));

        btnManagerMainMenuViewLogActivity.setBackground(new java.awt.Color(102, 102, 102));
        btnManagerMainMenuViewLogActivity.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnManagerMainMenuViewLogActivity.setForeground(new java.awt.Color(255, 255, 255));
        btnManagerMainMenuViewLogActivity.setText("View Log Activity");
        btnManagerMainMenuViewLogActivity.setToolTipText("");
        btnManagerMainMenuViewLogActivity.setBorder(null);
        btnManagerMainMenuViewLogActivity.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManagerMainMenuViewLogActivity.setDefaultCapable(false);
        btnManagerMainMenuViewLogActivity.setName(""); // NOI18N
        btnManagerMainMenuViewLogActivity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerMainMenuViewLogActivityActionPerformed(evt);
            }
        });
        pnlMainMenuBackground.add(btnManagerMainMenuViewLogActivity, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 540, 192, 45));

        pnlWesternFood2.setBackground(new java.awt.Color(71, 71, 71));

        javax.swing.GroupLayout pnlWesternFood2Layout = new javax.swing.GroupLayout(pnlWesternFood2);
        pnlWesternFood2.setLayout(pnlWesternFood2Layout);
        pnlWesternFood2Layout.setHorizontalGroup(
            pnlWesternFood2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 205, Short.MAX_VALUE)
        );
        pnlWesternFood2Layout.setVerticalGroup(
            pnlWesternFood2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnlMainMenuBackground.add(pnlWesternFood2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 450, -1, -1));

        btnManagerMainMenuLogOut.setBackground(new java.awt.Color(102, 102, 102));
        btnManagerMainMenuLogOut.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnManagerMainMenuLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnManagerMainMenuLogOut.setText("LOG OUT");
        btnManagerMainMenuLogOut.setToolTipText("");
        btnManagerMainMenuLogOut.setBorder(null);
        btnManagerMainMenuLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManagerMainMenuLogOut.setDefaultCapable(false);
        btnManagerMainMenuLogOut.setName(""); // NOI18N
        btnManagerMainMenuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerMainMenuLogOutActionPerformed(evt);
            }
        });
        pnlMainMenuBackground.add(btnManagerMainMenuLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 610, 192, 45));

        btnManagerMainMenuEndUserRegistration.setBackground(new java.awt.Color(102, 102, 102));
        btnManagerMainMenuEndUserRegistration.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnManagerMainMenuEndUserRegistration.setForeground(new java.awt.Color(255, 255, 255));
        btnManagerMainMenuEndUserRegistration.setText("End User Registration");
        btnManagerMainMenuEndUserRegistration.setToolTipText("");
        btnManagerMainMenuEndUserRegistration.setBorder(null);
        btnManagerMainMenuEndUserRegistration.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManagerMainMenuEndUserRegistration.setDefaultCapable(false);
        btnManagerMainMenuEndUserRegistration.setName(""); // NOI18N
        btnManagerMainMenuEndUserRegistration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerMainMenuEndUserRegistrationActionPerformed(evt);
            }
        });
        pnlMainMenuBackground.add(btnManagerMainMenuEndUserRegistration, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 192, 45));

        btnManagerMainMenuUpdateMenu.setBackground(new java.awt.Color(102, 102, 102));
        btnManagerMainMenuUpdateMenu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnManagerMainMenuUpdateMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnManagerMainMenuUpdateMenu.setText("Update Menu");
        btnManagerMainMenuUpdateMenu.setToolTipText("");
        btnManagerMainMenuUpdateMenu.setBorder(null);
        btnManagerMainMenuUpdateMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManagerMainMenuUpdateMenu.setDefaultCapable(false);
        btnManagerMainMenuUpdateMenu.setName(""); // NOI18N
        btnManagerMainMenuUpdateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerMainMenuUpdateMenuActionPerformed(evt);
            }
        });
        pnlMainMenuBackground.add(btnManagerMainMenuUpdateMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 192, 45));

        btnManagerMainMenuUpdateMenuCategory.setBackground(new java.awt.Color(102, 102, 102));
        btnManagerMainMenuUpdateMenuCategory.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnManagerMainMenuUpdateMenuCategory.setForeground(new java.awt.Color(255, 255, 255));
        btnManagerMainMenuUpdateMenuCategory.setText("Update Menu Category");
        btnManagerMainMenuUpdateMenuCategory.setToolTipText("");
        btnManagerMainMenuUpdateMenuCategory.setBorder(null);
        btnManagerMainMenuUpdateMenuCategory.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManagerMainMenuUpdateMenuCategory.setDefaultCapable(false);
        btnManagerMainMenuUpdateMenuCategory.setName(""); // NOI18N
        btnManagerMainMenuUpdateMenuCategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerMainMenuUpdateMenuCategoryActionPerformed(evt);
            }
        });
        pnlMainMenuBackground.add(btnManagerMainMenuUpdateMenuCategory, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 192, 45));

        btnManagerMainMenuViewSalesReport.setBackground(new java.awt.Color(102, 102, 102));
        btnManagerMainMenuViewSalesReport.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnManagerMainMenuViewSalesReport.setForeground(new java.awt.Color(255, 255, 255));
        btnManagerMainMenuViewSalesReport.setText("View Sales Report");
        btnManagerMainMenuViewSalesReport.setToolTipText("");
        btnManagerMainMenuViewSalesReport.setBorder(null);
        btnManagerMainMenuViewSalesReport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManagerMainMenuViewSalesReport.setDefaultCapable(false);
        btnManagerMainMenuViewSalesReport.setName(""); // NOI18N
        btnManagerMainMenuViewSalesReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerMainMenuViewSalesReportActionPerformed(evt);
            }
        });
        pnlMainMenuBackground.add(btnManagerMainMenuViewSalesReport, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 192, 45));

        btnManagerMainMenuViewFeedback.setBackground(new java.awt.Color(102, 102, 102));
        btnManagerMainMenuViewFeedback.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnManagerMainMenuViewFeedback.setForeground(new java.awt.Color(255, 255, 255));
        btnManagerMainMenuViewFeedback.setText("View Feedback");
        btnManagerMainMenuViewFeedback.setToolTipText("");
        btnManagerMainMenuViewFeedback.setBorder(null);
        btnManagerMainMenuViewFeedback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManagerMainMenuViewFeedback.setDefaultCapable(false);
        btnManagerMainMenuViewFeedback.setName(""); // NOI18N
        btnManagerMainMenuViewFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerMainMenuViewFeedbackActionPerformed(evt);
            }
        });
        pnlMainMenuBackground.add(btnManagerMainMenuViewFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 192, 45));

        lblManagerMainMenuWelcomeTitle.setBackground(new java.awt.Color(71, 71, 71));
        lblManagerMainMenuWelcomeTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblManagerMainMenuWelcomeTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblManagerMainMenuWelcomeTitle.setText("Welcome,");
        pnlMainMenuBackground.add(lblManagerMainMenuWelcomeTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 120, 53));

        lblManagerMainMenuName.setBackground(new java.awt.Color(71, 71, 71));
        lblManagerMainMenuName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblManagerMainMenuName.setForeground(new java.awt.Color(255, 255, 255));
        lblManagerMainMenuName.setText("Manager");
        pnlMainMenuBackground.add(lblManagerMainMenuName, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 40, 180, 53));

        btnManagerMainMenuViewUser.setBackground(new java.awt.Color(102, 102, 102));
        btnManagerMainMenuViewUser.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnManagerMainMenuViewUser.setForeground(new java.awt.Color(255, 255, 255));
        btnManagerMainMenuViewUser.setText("View User");
        btnManagerMainMenuViewUser.setToolTipText("");
        btnManagerMainMenuViewUser.setBorder(null);
        btnManagerMainMenuViewUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManagerMainMenuViewUser.setDefaultCapable(false);
        btnManagerMainMenuViewUser.setName(""); // NOI18N
        btnManagerMainMenuViewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagerMainMenuViewUserActionPerformed(evt);
            }
        });
        pnlMainMenuBackground.add(btnManagerMainMenuViewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 192, 45));

        getContentPane().add(pnlMainMenuBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnManagerMainMenuEndUserRegistrationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerMainMenuEndUserRegistrationActionPerformed
        // This button will open the End User Registration Form
        this.setVisible(false);
        frmManagerEndUserRegistration frmMEUR = new frmManagerEndUserRegistration(manager_id, manager_name, manager_pass, manager_role);
        frmMEUR.setVisible(true);
        logger.info(manager_role + ": " + manager_name + " " + "selected End User Registration");
    }//GEN-LAST:event_btnManagerMainMenuEndUserRegistrationActionPerformed

    private void btnManagerMainMenuUpdateMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerMainMenuUpdateMenuActionPerformed
        // This button will open the Update Menu Form
        this.setVisible(false);
        frmManagerUpdateMenu frmMUM = new frmManagerUpdateMenu(manager_id, manager_name, manager_pass, manager_role);
        frmMUM.setVisible(true);
        logger.info(manager_role + ": " + manager_name + " " + "selected Update Menu");
    }//GEN-LAST:event_btnManagerMainMenuUpdateMenuActionPerformed

    private void btnManagerMainMenuUpdateMenuCategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerMainMenuUpdateMenuCategoryActionPerformed
        // This button will open the Update Menu Category Form
        this.setVisible(false);
        frmManagerUpdateMenuCategories frmMUMC = new frmManagerUpdateMenuCategories(manager_id, manager_name, manager_pass, manager_role);
        frmMUMC.setVisible(true);
        logger.info(manager_role + ": " + manager_name + " " + "selected Update Menu Category");
    }//GEN-LAST:event_btnManagerMainMenuUpdateMenuCategoryActionPerformed

    private void btnManagerMainMenuViewSalesReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerMainMenuViewSalesReportActionPerformed
        // This button will open the Sales Report Form
        this.setVisible(false);
        frmManagerSalesReport frmMSR = new frmManagerSalesReport(manager_id, manager_name, manager_pass, manager_role);
        frmMSR.setVisible(true);
        logger.info(manager_role + ": " + manager_name + " " + "selected View Sales Report");
    }//GEN-LAST:event_btnManagerMainMenuViewSalesReportActionPerformed

    private void btnManagerMainMenuViewFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerMainMenuViewFeedbackActionPerformed
        // This button will open the View Feedback Form
        this.setVisible(false);
        frmManagerViewFeedback frmMVF = new frmManagerViewFeedback(manager_id, manager_name, manager_pass, manager_role);
        frmMVF.setVisible(true);
        logger.info(manager_role + ": " + manager_name + " " + "selected View Feedback");
    }//GEN-LAST:event_btnManagerMainMenuViewFeedbackActionPerformed

    private void btnManagerMainMenuViewLogActivityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerMainMenuViewLogActivityActionPerformed
        // This button will open the View User form
        this.setVisible(false);
        frmManagerViewLogActivity frmMVU = new frmManagerViewLogActivity(manager_id, manager_name, manager_pass, manager_role);
        frmMVU.setVisible(true);
        logger.info(manager_role + ": " + manager_name + " " + "selected View Log Activity");
    }//GEN-LAST:event_btnManagerMainMenuViewLogActivityActionPerformed

    private void btnManagerMainMenuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerMainMenuLogOutActionPerformed
        this.dispose();
        frmLogin loginform = new frmLogin();
        loginform.setVisible(true);
        logger.info(manager_role + ": " + manager_name + " " + "has logged out");
    }//GEN-LAST:event_btnManagerMainMenuLogOutActionPerformed

    private void btnManagerMainMenuViewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagerMainMenuViewUserActionPerformed
        this.setVisible(false);
        frmManagerViewUser frmvu = new frmManagerViewUser(manager_id, manager_name, manager_pass, manager_role);
        frmvu.setVisible(true);
        logger.info(manager_role + ": " + manager_name + " " + "selected View User");
    }//GEN-LAST:event_btnManagerMainMenuViewUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmManagerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmManagerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmManagerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmManagerMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmManagerMainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManagerMainMenuEndUserRegistration;
    private javax.swing.JButton btnManagerMainMenuLogOut;
    private javax.swing.JButton btnManagerMainMenuUpdateMenu;
    private javax.swing.JButton btnManagerMainMenuUpdateMenuCategory;
    private javax.swing.JButton btnManagerMainMenuViewFeedback;
    private javax.swing.JButton btnManagerMainMenuViewLogActivity;
    private javax.swing.JButton btnManagerMainMenuViewSalesReport;
    private javax.swing.JButton btnManagerMainMenuViewUser;
    private javax.swing.JLabel lblManagerMainMenuName;
    private javax.swing.JLabel lblManagerMainMenuWelcomeTitle;
    private javax.swing.JPanel pnlMainMenuBackground;
    private javax.swing.JPanel pnlMalayFood;
    private javax.swing.JPanel pnlWesternFood2;
    // End of variables declaration//GEN-END:variables
}
