/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms.Manager;

import forms.Login.frmLogin;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import org.apache.logging.log4j.LogManager;

/**
 *
 * @author User
 */
public class frmManagerViewFeedback extends javax.swing.JFrame {

    /**
     * Creates new form frmCustMenuCategories
     */
    
    private String manager_id;
    private String manager_name;
    private String manager_pass;
    private String manager_role;
    
    private static final org.apache.logging.log4j.Logger logger = LogManager.getLogger(frmManagerViewFeedback.class);
    
    public frmManagerViewFeedback() {
        initComponents();
        feedbackFiletoTable();
        Question1Analysis();
        Question2Analysis();
    }
    
    public frmManagerViewFeedback(String id, String name, String pass, String role) {
        initComponents();
        this.manager_id = id;
        this.manager_name = name;
        this.manager_pass = pass;
        this.manager_role = role;
        
        feedbackFiletoTable();
        Question1Analysis();
        Question2Analysis();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlViewFeedbackBackground = new javax.swing.JPanel();
        lblViewFeedbackTitle = new javax.swing.JLabel();
        btnBackViewFeedback = new javax.swing.JButton();
        pnlInnerViewFeedbackBackground = new javax.swing.JPanel();
        lblViewFeedbackListTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblViewFeedbackList = new javax.swing.JTable();
        lblViewFeedBackQuestion1Option5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txaViewFeedBackQuestion3 = new javax.swing.JTextArea();
        lblViewFeedBackQuestion3Title = new javax.swing.JLabel();
        lblViewFeedBackQuestion1Option3Amount = new javax.swing.JLabel();
        lblViewFeedBackQuestion1Option2 = new javax.swing.JLabel();
        lblViewFeedBackQuestion1Option3 = new javax.swing.JLabel();
        lblViewFeedBackQuestion1Option4 = new javax.swing.JLabel();
        lblViewFeedBackQuestion1Option1 = new javax.swing.JLabel();
        lblViewFeedBackQuestion1Option5Amount = new javax.swing.JLabel();
        lblViewFeedBackQuestion1Option2Amount = new javax.swing.JLabel();
        lblViewFeedBackQuestion1Option1Amount = new javax.swing.JLabel();
        lblViewFeedBackQuestion1Option4Amount = new javax.swing.JLabel();
        lblViewFeedBackQuestion1Title = new javax.swing.JLabel();
        lblViewFeedBackQuestion2OptionYes = new javax.swing.JLabel();
        lblViewFeedBackQuestion2OptionNo = new javax.swing.JLabel();
        lblViewFeedBackQuestion2OptionYesAmount = new javax.swing.JLabel();
        lblViewFeedBackQuestion2OptionNoAmount = new javax.swing.JLabel();
        lblViewFeedBackQuestion2Title = new javax.swing.JLabel();
        lblViewFeedbackListIDTitle = new javax.swing.JLabel();
        lblViewFeedbackListID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Feedback");
        setBackground(new java.awt.Color(51, 51, 51));
        setName("frmCustMenuCategories"); // NOI18N
        setResizable(false);

        pnlViewFeedbackBackground.setBackground(new java.awt.Color(51, 51, 51));
        pnlViewFeedbackBackground.setName("frmCustMenuCategories"); // NOI18N
        pnlViewFeedbackBackground.setPreferredSize(new java.awt.Dimension(1230, 700));
        pnlViewFeedbackBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblViewFeedbackTitle.setBackground(new java.awt.Color(71, 71, 71));
        lblViewFeedbackTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblViewFeedbackTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblViewFeedbackTitle.setText("View Feedback");
        pnlViewFeedbackBackground.add(lblViewFeedbackTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 606, 53));

        btnBackViewFeedback.setBackground(new java.awt.Color(102, 102, 102));
        btnBackViewFeedback.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnBackViewFeedback.setForeground(new java.awt.Color(255, 255, 255));
        btnBackViewFeedback.setText("BACK");
        btnBackViewFeedback.setToolTipText("");
        btnBackViewFeedback.setBorder(null);
        btnBackViewFeedback.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBackViewFeedback.setDefaultCapable(false);
        btnBackViewFeedback.setName(""); // NOI18N
        btnBackViewFeedback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackViewFeedbackActionPerformed(evt);
            }
        });
        pnlViewFeedbackBackground.add(btnBackViewFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 192, 45));

        pnlInnerViewFeedbackBackground.setBackground(new java.awt.Color(71, 71, 71));
        pnlInnerViewFeedbackBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblViewFeedbackListTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblViewFeedbackListTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblViewFeedbackListTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblViewFeedbackListTitle.setText("Feedback List");
        pnlInnerViewFeedbackBackground.add(lblViewFeedbackListTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 200, 40));

        tblViewFeedbackList.setAutoCreateRowSorter(true);
        tblViewFeedbackList.setBackground(new java.awt.Color(71, 71, 71));
        tblViewFeedbackList.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblViewFeedbackList.setForeground(new java.awt.Color(255, 255, 255));
        tblViewFeedbackList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Customer Name", "Question_1", "Question_2", "Question 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblViewFeedbackList.getTableHeader().setReorderingAllowed(false);
        tblViewFeedbackList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblViewFeedbackListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblViewFeedbackList);
        if (tblViewFeedbackList.getColumnModel().getColumnCount() > 0) {
            tblViewFeedbackList.getColumnModel().getColumn(0).setMaxWidth(30);
            tblViewFeedbackList.getColumnModel().getColumn(1).setMinWidth(100);
            tblViewFeedbackList.getColumnModel().getColumn(1).setMaxWidth(150);
            tblViewFeedbackList.getColumnModel().getColumn(2).setMaxWidth(100);
            tblViewFeedbackList.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        pnlInnerViewFeedbackBackground.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 790, 190));

        lblViewFeedBackQuestion1Option5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblViewFeedBackQuestion1Option5.setForeground(new java.awt.Color(255, 255, 255));
        lblViewFeedBackQuestion1Option5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewFeedBackQuestion1Option5.setText("5");
        lblViewFeedBackQuestion1Option5.setToolTipText("");
        lblViewFeedBackQuestion1Option5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlInnerViewFeedbackBackground.add(lblViewFeedBackQuestion1Option5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, 30, 30));

        txaViewFeedBackQuestion3.setBackground(new java.awt.Color(51, 51, 51));
        txaViewFeedBackQuestion3.setColumns(20);
        txaViewFeedBackQuestion3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txaViewFeedBackQuestion3.setForeground(new java.awt.Color(255, 255, 255));
        txaViewFeedBackQuestion3.setLineWrap(true);
        txaViewFeedBackQuestion3.setRows(5);
        txaViewFeedBackQuestion3.setToolTipText("");
        jScrollPane2.setViewportView(txaViewFeedBackQuestion3);

        pnlInnerViewFeedbackBackground.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, 320, 130));

        lblViewFeedBackQuestion3Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblViewFeedBackQuestion3Title.setForeground(new java.awt.Color(255, 255, 255));
        lblViewFeedBackQuestion3Title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblViewFeedBackQuestion3Title.setText("Question 3");
        lblViewFeedBackQuestion3Title.setToolTipText("");
        pnlInnerViewFeedbackBackground.add(lblViewFeedBackQuestion3Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, 100, 40));

        lblViewFeedBackQuestion1Option3Amount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblViewFeedBackQuestion1Option3Amount.setForeground(new java.awt.Color(255, 255, 255));
        lblViewFeedBackQuestion1Option3Amount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewFeedBackQuestion1Option3Amount.setText("0");
        lblViewFeedBackQuestion1Option3Amount.setToolTipText("");
        pnlInnerViewFeedbackBackground.add(lblViewFeedBackQuestion1Option3Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 30, 30));

        lblViewFeedBackQuestion1Option2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblViewFeedBackQuestion1Option2.setForeground(new java.awt.Color(255, 255, 255));
        lblViewFeedBackQuestion1Option2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewFeedBackQuestion1Option2.setText("2");
        lblViewFeedBackQuestion1Option2.setToolTipText("");
        lblViewFeedBackQuestion1Option2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlInnerViewFeedbackBackground.add(lblViewFeedBackQuestion1Option2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 30, 30));

        lblViewFeedBackQuestion1Option3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblViewFeedBackQuestion1Option3.setForeground(new java.awt.Color(255, 255, 255));
        lblViewFeedBackQuestion1Option3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewFeedBackQuestion1Option3.setText("3");
        lblViewFeedBackQuestion1Option3.setToolTipText("");
        lblViewFeedBackQuestion1Option3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlInnerViewFeedbackBackground.add(lblViewFeedBackQuestion1Option3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 430, 30, 30));

        lblViewFeedBackQuestion1Option4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblViewFeedBackQuestion1Option4.setForeground(new java.awt.Color(255, 255, 255));
        lblViewFeedBackQuestion1Option4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewFeedBackQuestion1Option4.setText("4");
        lblViewFeedBackQuestion1Option4.setToolTipText("");
        lblViewFeedBackQuestion1Option4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlInnerViewFeedbackBackground.add(lblViewFeedBackQuestion1Option4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 30, 30));

        lblViewFeedBackQuestion1Option1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblViewFeedBackQuestion1Option1.setForeground(new java.awt.Color(255, 255, 255));
        lblViewFeedBackQuestion1Option1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewFeedBackQuestion1Option1.setText("1");
        lblViewFeedBackQuestion1Option1.setToolTipText("");
        lblViewFeedBackQuestion1Option1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlInnerViewFeedbackBackground.add(lblViewFeedBackQuestion1Option1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 30, 30));

        lblViewFeedBackQuestion1Option5Amount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblViewFeedBackQuestion1Option5Amount.setForeground(new java.awt.Color(255, 255, 255));
        lblViewFeedBackQuestion1Option5Amount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewFeedBackQuestion1Option5Amount.setText("0");
        lblViewFeedBackQuestion1Option5Amount.setToolTipText("");
        pnlInnerViewFeedbackBackground.add(lblViewFeedBackQuestion1Option5Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 380, 30, 30));

        lblViewFeedBackQuestion1Option2Amount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblViewFeedBackQuestion1Option2Amount.setForeground(new java.awt.Color(255, 255, 255));
        lblViewFeedBackQuestion1Option2Amount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewFeedBackQuestion1Option2Amount.setText("0");
        lblViewFeedBackQuestion1Option2Amount.setToolTipText("");
        pnlInnerViewFeedbackBackground.add(lblViewFeedBackQuestion1Option2Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 380, 30, 30));

        lblViewFeedBackQuestion1Option1Amount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblViewFeedBackQuestion1Option1Amount.setForeground(new java.awt.Color(255, 255, 255));
        lblViewFeedBackQuestion1Option1Amount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewFeedBackQuestion1Option1Amount.setText("0");
        lblViewFeedBackQuestion1Option1Amount.setToolTipText("");
        pnlInnerViewFeedbackBackground.add(lblViewFeedBackQuestion1Option1Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 30, 30));

        lblViewFeedBackQuestion1Option4Amount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblViewFeedBackQuestion1Option4Amount.setForeground(new java.awt.Color(255, 255, 255));
        lblViewFeedBackQuestion1Option4Amount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewFeedBackQuestion1Option4Amount.setText("0");
        lblViewFeedBackQuestion1Option4Amount.setToolTipText("");
        pnlInnerViewFeedbackBackground.add(lblViewFeedBackQuestion1Option4Amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 330, 30, 30));

        lblViewFeedBackQuestion1Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblViewFeedBackQuestion1Title.setForeground(new java.awt.Color(255, 255, 255));
        lblViewFeedBackQuestion1Title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblViewFeedBackQuestion1Title.setText("Question 1");
        lblViewFeedBackQuestion1Title.setToolTipText("");
        pnlInnerViewFeedbackBackground.add(lblViewFeedBackQuestion1Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 110, 40));

        lblViewFeedBackQuestion2OptionYes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblViewFeedBackQuestion2OptionYes.setForeground(new java.awt.Color(255, 255, 255));
        lblViewFeedBackQuestion2OptionYes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewFeedBackQuestion2OptionYes.setText("YES");
        lblViewFeedBackQuestion2OptionYes.setToolTipText("");
        lblViewFeedBackQuestion2OptionYes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlInnerViewFeedbackBackground.add(lblViewFeedBackQuestion2OptionYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 40, 30));

        lblViewFeedBackQuestion2OptionNo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblViewFeedBackQuestion2OptionNo.setForeground(new java.awt.Color(255, 255, 255));
        lblViewFeedBackQuestion2OptionNo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewFeedBackQuestion2OptionNo.setText("NO");
        lblViewFeedBackQuestion2OptionNo.setToolTipText("");
        lblViewFeedBackQuestion2OptionNo.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlInnerViewFeedbackBackground.add(lblViewFeedBackQuestion2OptionNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 380, 40, 30));

        lblViewFeedBackQuestion2OptionYesAmount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblViewFeedBackQuestion2OptionYesAmount.setForeground(new java.awt.Color(255, 255, 255));
        lblViewFeedBackQuestion2OptionYesAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewFeedBackQuestion2OptionYesAmount.setText("0");
        lblViewFeedBackQuestion2OptionYesAmount.setToolTipText("");
        pnlInnerViewFeedbackBackground.add(lblViewFeedBackQuestion2OptionYesAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, 30, 30));

        lblViewFeedBackQuestion2OptionNoAmount.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblViewFeedBackQuestion2OptionNoAmount.setForeground(new java.awt.Color(255, 255, 255));
        lblViewFeedBackQuestion2OptionNoAmount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewFeedBackQuestion2OptionNoAmount.setText("0");
        lblViewFeedBackQuestion2OptionNoAmount.setToolTipText("");
        pnlInnerViewFeedbackBackground.add(lblViewFeedBackQuestion2OptionNoAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 30, 30));

        lblViewFeedBackQuestion2Title.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblViewFeedBackQuestion2Title.setForeground(new java.awt.Color(255, 255, 255));
        lblViewFeedBackQuestion2Title.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblViewFeedBackQuestion2Title.setText("Question 2");
        lblViewFeedBackQuestion2Title.setToolTipText("");
        pnlInnerViewFeedbackBackground.add(lblViewFeedBackQuestion2Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 100, 40));

        lblViewFeedbackListIDTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblViewFeedbackListIDTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblViewFeedbackListIDTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblViewFeedbackListIDTitle.setText("ID:");
        lblViewFeedbackListIDTitle.setToolTipText("");
        pnlInnerViewFeedbackBackground.add(lblViewFeedbackListIDTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 280, 30, 40));

        lblViewFeedbackListID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblViewFeedbackListID.setForeground(new java.awt.Color(255, 255, 255));
        lblViewFeedbackListID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewFeedbackListID.setToolTipText("");
        lblViewFeedbackListID.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pnlInnerViewFeedbackBackground.add(lblViewFeedbackListID, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 280, 50, 40));

        pnlViewFeedbackBackground.add(pnlInnerViewFeedbackBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 96, 990, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlViewFeedbackBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlViewFeedbackBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pnlViewFeedbackBackground.getAccessibleContext().setAccessibleName("View Feedback");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackViewFeedbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackViewFeedbackActionPerformed
        this.dispose();
        frmManagerMainMenu frmMMM = new frmManagerMainMenu(manager_id, manager_name, manager_pass, manager_role);
        frmMMM.setVisible(true);
        logger.info(manager_role + ": " + manager_name + " " + "Quit View Feedback back to Manager Main Menu");
    }//GEN-LAST:event_btnBackViewFeedbackActionPerformed

    private void tblViewFeedbackListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblViewFeedbackListMouseClicked
        getFeedbackDesc();
        logger.info(manager_role + ": " + manager_name + " " + "Selected a Feedback to view its Description");
    }//GEN-LAST:event_tblViewFeedbackListMouseClicked

    public void feedbackFiletoTable(){
        Feedback fb = new Feedback();
        fb.importFiletoTable();
    }
    
    public void Question1Analysis(){
        int r1 = 0;
        int r2 = 0;
        int r3 = 0;
        int r4 = 0;
        int r5 = 0;
        
        for(int i=0; i<tblViewFeedbackList.getRowCount(); i++){
            int ratings = Integer.parseInt(tblViewFeedbackList.getValueAt(i, 2).toString());
            
            switch(ratings){
                case 1:
                    r1 = r1 + 1;
                    break;
                case 2:
                    r2 = r2 + 1;
                    break;
                case 3:
                    r3 = r3 + 1;
                    break;
                case 4:
                    r4 = r4 + 1;
                    break;
                case 5:
                    r5 = r5 + 1;
                    break;
            }
        }
        
        lblViewFeedBackQuestion1Option1Amount.setText(Integer.toString(r1));
        lblViewFeedBackQuestion1Option2Amount.setText(Integer.toString(r2));
        lblViewFeedBackQuestion1Option3Amount.setText(Integer.toString(r3));
        lblViewFeedBackQuestion1Option4Amount.setText(Integer.toString(r4));
        lblViewFeedBackQuestion1Option5Amount.setText(Integer.toString(r5));
    }
    
    public void Question2Analysis(){
        int yes_count = 0;
        int no_count = 0;
        int choice_num = 0;
        
        for(int i=0; i<tblViewFeedbackList.getRowCount(); i++){
            String choice = tblViewFeedbackList.getValueAt(i, 3).toString();
            
            if(choice.equals("Yes")){
                choice_num = 1;
            }else if(choice.equals("No")){
                choice_num = 0;
            }
            
            switch(choice_num){
                case 0:
                    no_count = no_count + 1;
                    break;
                case 1:
                    yes_count = yes_count + 1;
                    break;
            }
        }
        
        lblViewFeedBackQuestion2OptionYesAmount.setText(Integer.toString(yes_count));
        lblViewFeedBackQuestion2OptionNoAmount.setText(Integer.toString(no_count));
    }
    
    public void getFeedbackDesc(){
        DefaultTableModel model = (DefaultTableModel)tblViewFeedbackList.getModel();
        int selectedRowIndex = tblViewFeedbackList.convertRowIndexToModel(tblViewFeedbackList.getSelectedRow());
        
        lblViewFeedbackListID.setText(model.getValueAt(selectedRowIndex, 0).toString());
        txaViewFeedBackQuestion3.setText(model.getValueAt(selectedRowIndex, 4).toString());
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmManagerViewFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmManagerViewFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmManagerViewFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmManagerViewFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmManagerViewFeedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackViewFeedback;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblViewFeedBackQuestion1Option1;
    private javax.swing.JLabel lblViewFeedBackQuestion1Option1Amount;
    private javax.swing.JLabel lblViewFeedBackQuestion1Option2;
    private javax.swing.JLabel lblViewFeedBackQuestion1Option2Amount;
    private javax.swing.JLabel lblViewFeedBackQuestion1Option3;
    private javax.swing.JLabel lblViewFeedBackQuestion1Option3Amount;
    private javax.swing.JLabel lblViewFeedBackQuestion1Option4;
    private javax.swing.JLabel lblViewFeedBackQuestion1Option4Amount;
    private javax.swing.JLabel lblViewFeedBackQuestion1Option5;
    private javax.swing.JLabel lblViewFeedBackQuestion1Option5Amount;
    private javax.swing.JLabel lblViewFeedBackQuestion1Title;
    private javax.swing.JLabel lblViewFeedBackQuestion2OptionNo;
    private javax.swing.JLabel lblViewFeedBackQuestion2OptionNoAmount;
    private javax.swing.JLabel lblViewFeedBackQuestion2OptionYes;
    private javax.swing.JLabel lblViewFeedBackQuestion2OptionYesAmount;
    private javax.swing.JLabel lblViewFeedBackQuestion2Title;
    private javax.swing.JLabel lblViewFeedBackQuestion3Title;
    private javax.swing.JLabel lblViewFeedbackListID;
    private javax.swing.JLabel lblViewFeedbackListIDTitle;
    private javax.swing.JLabel lblViewFeedbackListTitle;
    private javax.swing.JLabel lblViewFeedbackTitle;
    private javax.swing.JPanel pnlInnerViewFeedbackBackground;
    private javax.swing.JPanel pnlViewFeedbackBackground;
    public static javax.swing.JTable tblViewFeedbackList;
    private javax.swing.JTextArea txaViewFeedBackQuestion3;
    // End of variables declaration//GEN-END:variables
}
