/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms.Manager;

import forms.Login.frmLogin;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import org.apache.logging.log4j.LogManager;

/**
 *
 * @author Teoh Will Shen
 */
public class frmManagerViewLogActivity extends javax.swing.JFrame {

    ButtonGroup bg = new ButtonGroup();
    
    /**
     * Creates new form frmMangerViewUser
     */
    
    private String manager_id;
    private String manager_name;
    private String manager_pass;
    private String manager_role;
    
    private static final org.apache.logging.log4j.Logger logger = LogManager.getLogger(frmManagerViewLogActivity.class);
    
    public frmManagerViewLogActivity() {
        initComponents();
        addradiobuttonGroup();
        userFiletoTable();
    }
    
    public frmManagerViewLogActivity(String id, String name, String pass, String role) {
        initComponents();
        this.manager_id = id;
        this.manager_name = name;
        this.manager_pass = pass;
        this.manager_role = role;
        
        addradiobuttonGroup();
        userFiletoTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlViewLogActivityBackground = new javax.swing.JPanel();
        lblViewUser = new javax.swing.JLabel();
        btnViewLogActivityBack = new javax.swing.JButton();
        pnlInnerViewLogActivityBackground = new javax.swing.JPanel();
        lblLogActivityTableTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLogActivity = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        lblViewLogActivitySearchTitle = new javax.swing.JLabel();
        txtViewLogActivitySearch = new javax.swing.JTextField();
        btnViewLogActivitySearchUser = new javax.swing.JButton();
        lblViewLogActivityViewOnly = new javax.swing.JLabel();
        lblViewLogActivitySearchUsernameTitle = new javax.swing.JLabel();
        radViewLogActivityViewOnlyManager = new javax.swing.JRadioButton();
        radViewLogActivityViewOnlyCustomer = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("View Log Activity");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlViewLogActivityBackground.setBackground(new java.awt.Color(51, 51, 51));
        pnlViewLogActivityBackground.setName("frmCustMenuCategories"); // NOI18N
        pnlViewLogActivityBackground.setPreferredSize(new java.awt.Dimension(1230, 700));
        pnlViewLogActivityBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblViewUser.setBackground(new java.awt.Color(71, 71, 71));
        lblViewUser.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblViewUser.setForeground(new java.awt.Color(255, 255, 255));
        lblViewUser.setText("View Log Activity");
        pnlViewLogActivityBackground.add(lblViewUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 310, 53));

        btnViewLogActivityBack.setBackground(new java.awt.Color(102, 102, 102));
        btnViewLogActivityBack.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnViewLogActivityBack.setForeground(new java.awt.Color(255, 255, 255));
        btnViewLogActivityBack.setText("BACK");
        btnViewLogActivityBack.setToolTipText("");
        btnViewLogActivityBack.setBorder(null);
        btnViewLogActivityBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewLogActivityBack.setDefaultCapable(false);
        btnViewLogActivityBack.setName(""); // NOI18N
        btnViewLogActivityBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLogActivityBackActionPerformed(evt);
            }
        });
        pnlViewLogActivityBackground.add(btnViewLogActivityBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 192, 45));

        pnlInnerViewLogActivityBackground.setBackground(new java.awt.Color(71, 71, 71));
        pnlInnerViewLogActivityBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblLogActivityTableTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblLogActivityTableTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblLogActivityTableTitle.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblLogActivityTableTitle.setText("Log Activity");
        pnlInnerViewLogActivityBackground.add(lblLogActivityTableTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 200, 40));

        tblLogActivity.setAutoCreateRowSorter(true);
        tblLogActivity.setBackground(new java.awt.Color(71, 71, 71));
        tblLogActivity.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        tblLogActivity.setForeground(new java.awt.Color(255, 255, 255));
        tblLogActivity.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Levels", "Date", "Time", "Activity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLogActivity.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblLogActivity);
        if (tblLogActivity.getColumnModel().getColumnCount() > 0) {
            tblLogActivity.getColumnModel().getColumn(0).setMaxWidth(60);
            tblLogActivity.getColumnModel().getColumn(3).setMinWidth(500);
        }

        pnlInnerViewLogActivityBackground.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 790, 190));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setToolTipText("");
        pnlInnerViewLogActivityBackground.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 30, 30));

        lblViewLogActivitySearchTitle.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblViewLogActivitySearchTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblViewLogActivitySearchTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewLogActivitySearchTitle.setText("Search");
        lblViewLogActivitySearchTitle.setToolTipText("");
        pnlInnerViewLogActivityBackground.add(lblViewLogActivitySearchTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 80, 30));

        txtViewLogActivitySearch.setBackground(new java.awt.Color(51, 51, 51));
        txtViewLogActivitySearch.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        txtViewLogActivitySearch.setForeground(new java.awt.Color(255, 255, 255));
        txtViewLogActivitySearch.setBorder(null);
        pnlInnerViewLogActivityBackground.add(txtViewLogActivitySearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 260, 31));

        btnViewLogActivitySearchUser.setBackground(new java.awt.Color(102, 0, 248));
        btnViewLogActivitySearchUser.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        btnViewLogActivitySearchUser.setForeground(new java.awt.Color(255, 255, 255));
        btnViewLogActivitySearchUser.setText("SEARCH");
        btnViewLogActivitySearchUser.setToolTipText("");
        btnViewLogActivitySearchUser.setBorder(null);
        btnViewLogActivitySearchUser.setBorderPainted(false);
        btnViewLogActivitySearchUser.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewLogActivitySearchUser.setDefaultCapable(false);
        btnViewLogActivitySearchUser.setName(""); // NOI18N
        btnViewLogActivitySearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewLogActivitySearchUserActionPerformed(evt);
            }
        });
        pnlInnerViewLogActivityBackground.add(btnViewLogActivitySearchUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, 102, 37));

        lblViewLogActivityViewOnly.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblViewLogActivityViewOnly.setForeground(new java.awt.Color(255, 255, 255));
        lblViewLogActivityViewOnly.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewLogActivityViewOnly.setText("View Only");
        lblViewLogActivityViewOnly.setToolTipText("");
        pnlInnerViewLogActivityBackground.add(lblViewLogActivityViewOnly, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 280, 90, 40));

        lblViewLogActivitySearchUsernameTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblViewLogActivitySearchUsernameTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblViewLogActivitySearchUsernameTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewLogActivitySearchUsernameTitle.setText("Search Username");
        lblViewLogActivitySearchUsernameTitle.setToolTipText("");
        pnlInnerViewLogActivityBackground.add(lblViewLogActivitySearchUsernameTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 280, 160, 40));

        radViewLogActivityViewOnlyManager.setBackground(new java.awt.Color(51, 51, 51));
        radViewLogActivityViewOnlyManager.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        radViewLogActivityViewOnlyManager.setForeground(new java.awt.Color(255, 255, 255));
        radViewLogActivityViewOnlyManager.setText("Manager");
        radViewLogActivityViewOnlyManager.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radViewLogActivityViewOnlyManagerItemStateChanged(evt);
            }
        });
        pnlInnerViewLogActivityBackground.add(radViewLogActivityViewOnlyManager, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 330, -1, -1));

        radViewLogActivityViewOnlyCustomer.setBackground(new java.awt.Color(51, 51, 51));
        radViewLogActivityViewOnlyCustomer.setFont(new java.awt.Font("Segoe UI Light", 0, 16)); // NOI18N
        radViewLogActivityViewOnlyCustomer.setForeground(new java.awt.Color(255, 255, 255));
        radViewLogActivityViewOnlyCustomer.setText("Customer");
        radViewLogActivityViewOnlyCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radViewLogActivityViewOnlyCustomerActionPerformed(evt);
            }
        });
        pnlInnerViewLogActivityBackground.add(radViewLogActivityViewOnlyCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 380, -1, -1));

        pnlViewLogActivityBackground.add(pnlInnerViewLogActivityBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 96, 990, 490));

        getContentPane().add(pnlViewLogActivityBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        pnlViewLogActivityBackground.getAccessibleContext().setAccessibleName("View User");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewLogActivitySearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLogActivitySearchUserActionPerformed
        searchingUserTable();
        logger.info(manager_role + ": " + manager_name + " " + "searched for a user");
    }//GEN-LAST:event_btnViewLogActivitySearchUserActionPerformed

    private void btnViewLogActivityBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewLogActivityBackActionPerformed
        this.dispose();
        frmManagerMainMenu frmMMM = new frmManagerMainMenu(manager_id, manager_name, manager_pass, manager_role);
        frmMMM.setVisible(true);
        logger.info(manager_role + ": " + manager_name + " " + "Quit View Log Activity back to Manager Main Menu");
    }//GEN-LAST:event_btnViewLogActivityBackActionPerformed

    private void radViewLogActivityViewOnlyCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radViewLogActivityViewOnlyCustomerActionPerformed
        String q = getSelected();
        filter(q);
        logger.info(manager_role + ": " + manager_name + " " + "View Customer Only");
    }//GEN-LAST:event_radViewLogActivityViewOnlyCustomerActionPerformed

    private void radViewLogActivityViewOnlyManagerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radViewLogActivityViewOnlyManagerItemStateChanged
        String q = getSelected();
        filter(q);
        logger.info(manager_role + ": " + manager_name + " " + "View Manager Only");
    }//GEN-LAST:event_radViewLogActivityViewOnlyManagerItemStateChanged
    
    private void filter(String q){
        DefaultTableModel model = (DefaultTableModel)tblLogActivity.getModel();
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        tblLogActivity.setRowSorter(tr);
        
        if(q != "None"){
            tr.setRowFilter(RowFilter.regexFilter(q));
        }else{
            tblLogActivity.setRowSorter(tr);
        }
    }

    private void addradiobuttonGroup(){
        bg.add(radViewLogActivityViewOnlyCustomer);
        bg.add(radViewLogActivityViewOnlyManager);
    }
    
    private String getSelected(){
        if(radViewLogActivityViewOnlyCustomer.isSelected()){
            return "Customer";
        }else if(radViewLogActivityViewOnlyManager.isSelected()){
            return "Manager";
        }else{
            return "None";
        }
    }
    
    public void userFiletoTable(){
        Log_Activity la = new Log_Activity();
        la.importFiletoTable();
    }
    
    public void searchingUserTable(){
        String searchText = txtViewLogActivitySearch.getText();
        
        Log_Activity la = new Log_Activity();
        la.searchInformation(searchText);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmManagerViewLogActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmManagerViewLogActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmManagerViewLogActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmManagerViewLogActivity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmManagerViewLogActivity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewLogActivityBack;
    private javax.swing.JButton btnViewLogActivitySearchUser;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblLogActivityTableTitle;
    private javax.swing.JLabel lblViewLogActivitySearchTitle;
    private javax.swing.JLabel lblViewLogActivitySearchUsernameTitle;
    private javax.swing.JLabel lblViewLogActivityViewOnly;
    private javax.swing.JLabel lblViewUser;
    private javax.swing.JPanel pnlInnerViewLogActivityBackground;
    private javax.swing.JPanel pnlViewLogActivityBackground;
    private javax.swing.JRadioButton radViewLogActivityViewOnlyCustomer;
    private javax.swing.JRadioButton radViewLogActivityViewOnlyManager;
    public static javax.swing.JTable tblLogActivity;
    private javax.swing.JTextField txtViewLogActivitySearch;
    // End of variables declaration//GEN-END:variables
}
