/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms.Customer;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import org.apache.logging.log4j.LogManager;

/**
 *
 * @author User
 */
public class frmCustFeedback extends javax.swing.JFrame {

    /**
     * Creates new form frmCustFeedback
     */
    
    private String Username;
    private String UserID;
    private String Password;
    private String UserRole;
    private String Date;
    private String Time;
    private int PaymentID;
    private int OrderID;
    
    private String Q1;
    private String Q2;
    private String Q3;
    
    private static final org.apache.logging.log4j.Logger logger = LogManager.getLogger(frmCustFeedback.class);
    
    public frmCustFeedback() {
        initComponents();
    }
    
    public frmCustFeedback(String ID, String u, String p, String r, String d, int pay, int ord) {
        UserID = ID;
        Username = u;
        Password = p;
        UserRole = r;
        Date = d;
        PaymentID = pay;
        OrderID = ord;
        initComponents();
    }
    
    public frmCustFeedback(String ID, String u, String p, String r, int pay, int ord) {
        UserID = ID;
        Username = u;
        Password = p;
        UserRole = r;
        PaymentID = pay;
        OrderID = ord;
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgQuestion2 = new javax.swing.ButtonGroup();
        pnlBackground = new javax.swing.JPanel();
        btnSubmit = new javax.swing.JButton();
        lblFeedback = new javax.swing.JLabel();
        lblQuestion2 = new javax.swing.JLabel();
        txtDigit1 = new javax.swing.JTextField();
        lblQuestion1 = new javax.swing.JLabel();
        btnYes = new javax.swing.JRadioButton();
        btnNo = new javax.swing.JRadioButton();
        lblQuestion3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaFeedback = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        pnlBackground.setBackground(new java.awt.Color(51, 51, 51));
        pnlBackground.setPreferredSize(new java.awt.Dimension(1230, 700));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSubmit.setBackground(new java.awt.Color(102, 102, 102));
        btnSubmit.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("SUBMIT");
        btnSubmit.setToolTipText("");
        btnSubmit.setBorder(null);
        btnSubmit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSubmit.setDefaultCapable(false);
        btnSubmit.setFocusPainted(false);
        btnSubmit.setName(""); // NOI18N
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        pnlBackground.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(926, 601, 203, 46));

        lblFeedback.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblFeedback.setForeground(new java.awt.Color(255, 255, 255));
        lblFeedback.setText("FEEDBACK");
        pnlBackground.add(lblFeedback, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        lblQuestion2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblQuestion2.setForeground(new java.awt.Color(255, 255, 255));
        lblQuestion2.setText("2. Do you prefer ordering food in person?");
        lblQuestion2.setToolTipText("");
        pnlBackground.add(lblQuestion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 223, -1, -1));

        txtDigit1.setBackground(new java.awt.Color(71, 71, 71));
        txtDigit1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtDigit1.setForeground(new java.awt.Color(255, 255, 255));
        txtDigit1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtDigit1.setText("0");
        txtDigit1.setToolTipText("");
        txtDigit1.setBorder(null);
        txtDigit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtDigit1MouseClicked(evt);
            }
        });
        pnlBackground.add(txtDigit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 141, -1, 44));

        lblQuestion1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblQuestion1.setForeground(new java.awt.Color(255, 255, 255));
        lblQuestion1.setText("1. From 1 to 5, how much would you rate the food ordering system?");
        lblQuestion1.setToolTipText("");
        pnlBackground.add(lblQuestion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 101, -1, -1));

        btnYes.setBackground(new java.awt.Color(51, 51, 51));
        btgQuestion2.add(btnYes);
        btnYes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnYes.setForeground(new java.awt.Color(255, 255, 255));
        btnYes.setText("Yes");
        btnYes.setBorder(null);
        pnlBackground.add(btnYes, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 282, -1, -1));

        btnNo.setBackground(new java.awt.Color(51, 51, 51));
        btgQuestion2.add(btnNo);
        btnNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnNo.setForeground(new java.awt.Color(255, 255, 255));
        btnNo.setText("No");
        btnNo.setBorder(null);
        pnlBackground.add(btnNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 282, -1, -1));

        lblQuestion3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblQuestion3.setForeground(new java.awt.Color(255, 255, 255));
        lblQuestion3.setText("3. Feedback");
        lblQuestion3.setToolTipText("");
        pnlBackground.add(lblQuestion3, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 340, -1, -1));

        txaFeedback.setBackground(new java.awt.Color(71, 71, 71));
        txaFeedback.setColumns(20);
        txaFeedback.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        txaFeedback.setForeground(new java.awt.Color(255, 255, 255));
        txaFeedback.setRows(5);
        txaFeedback.setBorder(null);
        jScrollPane1.setViewportView(txaFeedback);

        pnlBackground.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 390, 1020, 172));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 1191, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        btnYes.setActionCommand("Yes");
        btnNo.setActionCommand("No");
        
        Feedback custFeedback = new Feedback(UserID,Username,Password,String.valueOf(PaymentID),String.valueOf(OrderID));
        
        int feedbackid = custFeedback.getID();
        custFeedback.sendFeedback(feedbackid);

        this.toBack();
        this.setVisible(false);
        frmCustMainMenu menu = new frmCustMainMenu(UserID,Username,Password);
        menu.setVisible(true);
        this.dispose();
        
        logger.info(UserRole + ": " + Username + " " + "Submitted the Feedback");
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void txtDigit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtDigit1MouseClicked
        // TODO add your handling code here:
        txtDigit1.setText("");
    }//GEN-LAST:event_txtDigit1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCustFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCustFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCustFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCustFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCustFeedback().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.ButtonGroup btgQuestion2;
    public static javax.swing.JRadioButton btnNo;
    private javax.swing.JButton btnSubmit;
    public static javax.swing.JRadioButton btnYes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFeedback;
    private javax.swing.JLabel lblQuestion1;
    private javax.swing.JLabel lblQuestion2;
    private javax.swing.JLabel lblQuestion3;
    private javax.swing.JPanel pnlBackground;
    public static javax.swing.JTextArea txaFeedback;
    public static javax.swing.JTextField txtDigit1;
    // End of variables declaration//GEN-END:variables
}
