/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms.Customer;


import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.table.DefaultTableModel;
import java.math.RoundingMode;
import java.text.DecimalFormat;
import java.util.Scanner;
import org.apache.logging.log4j.LogManager;

/**
 *
 * @author User
 */
public class frmCustCart extends javax.swing.JFrame {

    /**
     * Creates new form frmCustCart
     */
    private String UserID;
    private String Username;
    private String Password;
    private String UserRole;
    private String Date;
    private String Time;
    private String PaymentID;
    private String OrderID;
    
    private static final DecimalFormat df = new DecimalFormat("0.00");
    
    private static final org.apache.logging.log4j.Logger logger = LogManager.getLogger(frmCustCart.class);
    
    public frmCustCart() {
        initComponents();
    }
    
    public frmCustCart(String ID, String u, String p, String r) {
        UserID = ID;
        Username = u;
        Password = p;
        UserRole = r;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblAPUCafeteriaCart = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        btnPayOrder = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCart = new javax.swing.JTable();
        lblTotal = new javax.swing.JLabel();
        lblCalculatedTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cart");
        setName("frmCustCart"); // NOI18N
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        pnlBackground.setBackground(new java.awt.Color(51, 51, 51));
        pnlBackground.setPreferredSize(new java.awt.Dimension(450, 700));
        pnlBackground.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnlBackgroundComponentShown(evt);
            }
        });
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblAPUCafeteriaCart.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblAPUCafeteriaCart.setForeground(new java.awt.Color(255, 255, 255));
        lblAPUCafeteriaCart.setText("APU CAFETERIA CART");
        pnlBackground.add(lblAPUCafeteriaCart, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, -1, -1));

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<");
        btnBack.setToolTipText("");
        btnBack.setBorder(null);
        btnBack.setBorderPainted(false);
        btnBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBack.setDefaultCapable(false);
        btnBack.setFocusPainted(false);
        btnBack.setName(""); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlBackground.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 34, 47, 48));

        btnPayOrder.setBackground(new java.awt.Color(102, 102, 102));
        btnPayOrder.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnPayOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnPayOrder.setText("PAY ORDER");
        btnPayOrder.setToolTipText("");
        btnPayOrder.setBorder(null);
        btnPayOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPayOrder.setDefaultCapable(false);
        btnPayOrder.setFocusPainted(false);
        btnPayOrder.setName(""); // NOI18N
        btnPayOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayOrderActionPerformed(evt);
            }
        });
        pnlBackground.add(btnPayOrder, new org.netbeans.lib.awtextra.AbsoluteConstraints(122, 611, 203, 37));

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        tblCart.setAutoCreateRowSorter(true);
        tblCart.setBackground(new java.awt.Color(102, 102, 102));
        tblCart.setForeground(new java.awt.Color(255, 255, 255));
        tblCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Food ID", "Food Category", "Food Name", "Quantity", "Price", "Total Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCart.setCellSelectionEnabled(true);
        tblCart.setGridColor(new java.awt.Color(102, 102, 102));
        tblCart.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tblCart.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblCart.setShowGrid(true);
        jScrollPane1.setViewportView(tblCart);

        pnlBackground.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 370, 450));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotal.setForeground(new java.awt.Color(255, 255, 255));
        lblTotal.setText("TOTAL");
        pnlBackground.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        lblCalculatedTotal.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        lblCalculatedTotal.setForeground(new java.awt.Color(51, 153, 0));
        lblCalculatedTotal.setText("RM 0.00");
        pnlBackground.add(lblCalculatedTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 70, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.toBack();
        this.setVisible(false);
        frmCustOrderingMenu order = new frmCustOrderingMenu(UserID,Username,Password,UserRole);
        order.setVisible(true);
        this.dispose();
        logger.info(UserRole + ": " + Username + " " + "Quit Cart back to Ordering Menu");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPayOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayOrderActionPerformed
        // TODO add your handling code here:
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        LocalDate localDate = LocalDate.now();
        
        Date = dtf.format(localDate).toString();
        System.out.println(Date);
        
        
        Order custOrder = new Order(UserID,Username,Password,Date,OrderID);
        
        int order_id = custOrder.getID();
        OrderID = String.valueOf(order_id);
        System.out.println("ORDER ID IS "+OrderID);
        custOrder.sendOrder(OrderID);
        
        Payment custPayment = new Payment(UserID,Username,Password,Date);

        int paymentID = custPayment.getID();
        PaymentID = String.valueOf(paymentID);
        
        String totalamount = custOrder.getTotalAmount();
        custPayment.pay(paymentID, OrderID,totalamount);
        this.toBack();
        this.setVisible(false);
        frmCustReceipt custReceipt = new frmCustReceipt(UserID,Username,Password,UserRole,Date,PaymentID,OrderID);
        custReceipt.toFront();
        custReceipt.setVisible(true);
        this.dispose();
        logger.info(UserRole + ": " + Username + " " + "selected Pay Order and will get Receipt");
    }//GEN-LAST:event_btnPayOrderActionPerformed

    private void pnlBackgroundComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnlBackgroundComponentShown
        
    }//GEN-LAST:event_pnlBackgroundComponentShown

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        Payment custPayment = new Payment();
        custPayment.getFoodCart();
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCustCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCustCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCustCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCustCart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCustCart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPayOrder;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAPUCafeteriaCart;
    public static javax.swing.JLabel lblCalculatedTotal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel pnlBackground;
    public static javax.swing.JTable tblCart;
    // End of variables declaration//GEN-END:variables
}
