/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms.Customer;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.logging.log4j.LogManager;

/**
 *
 * @author User
 */
public class frmCustTransactionRecord extends javax.swing.JFrame {

    /**
     * Creates new form frmCustMenuChineseFood
     */
    
    private static String Username;
    private static String Password;
    private static String UserID;
    private static String UserRole;
    private static String Date;
    private static String PaymentID;
    private static String OrderID;
    
    private static final org.apache.logging.log4j.Logger logger = LogManager.getLogger(frmCustTransactionRecord.class);
    
    public frmCustTransactionRecord() {
        initComponents();
    }
    
    public frmCustTransactionRecord(String ID, String u, String p, String r) {
        UserID = ID;
        Username = u;
        Password = p;
        UserRole = r;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblCategoryName = new javax.swing.JLabel();
        btnViewReceipt = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTransactionRecord = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Food");
        setName("frmCustMenuFood"); // NOI18N
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        pnlBackground.setBackground(new java.awt.Color(51, 51, 51));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCategoryName.setBackground(new java.awt.Color(71, 71, 71));
        lblCategoryName.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblCategoryName.setForeground(new java.awt.Color(255, 255, 255));
        lblCategoryName.setText("TRANSACTION RECORDS");
        pnlBackground.add(lblCategoryName, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 606, 53));

        btnViewReceipt.setBackground(new java.awt.Color(102, 102, 102));
        btnViewReceipt.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnViewReceipt.setForeground(new java.awt.Color(255, 255, 255));
        btnViewReceipt.setText("VIEW RECEIPT");
        btnViewReceipt.setToolTipText("");
        btnViewReceipt.setBorder(null);
        btnViewReceipt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnViewReceipt.setDefaultCapable(false);
        btnViewReceipt.setFocusPainted(false);
        btnViewReceipt.setName(""); // NOI18N
        btnViewReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReceiptActionPerformed(evt);
            }
        });
        pnlBackground.add(btnViewReceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 590, 203, 46));

        btnBack.setBackground(new java.awt.Color(102, 102, 102));
        btnBack.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("<");
        btnBack.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlBackground.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 50, 50));

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 102));
        jScrollPane1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));

        tblTransactionRecord.setAutoCreateRowSorter(true);
        tblTransactionRecord.setBackground(new java.awt.Color(102, 102, 102));
        tblTransactionRecord.setForeground(new java.awt.Color(255, 255, 255));
        tblTransactionRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Payment ID", "Order ID", "Paid Amount", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTransactionRecord.setGridColor(new java.awt.Color(102, 102, 102));
        tblTransactionRecord.setSelectionBackground(new java.awt.Color(51, 51, 51));
        tblTransactionRecord.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblTransactionRecord.setShowGrid(true);
        jScrollPane1.setViewportView(tblTransactionRecord);

        pnlBackground.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 1130, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 1216, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, 689, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.toBack();
        this.setVisible(false);
        frmCustMainMenu menu = new frmCustMainMenu();
        menu.setVisible(true);
        this.dispose();
        logger.info(UserRole + ": " + Username + " " + "Quit Transaction History back to Customer Main Menu");
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReceiptActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblTransactionRecord.getModel();
        
        if(tblTransactionRecord.getSelectedRow()!=-1){
            int rowcount = tblTransactionRecord.getSelectedRow();
        
            String paymentid = tblTransactionRecord.getValueAt(rowcount, 0).toString();
            PaymentID = paymentid;
            String orderid = tblTransactionRecord.getValueAt(rowcount, 1).toString();
            OrderID = orderid;
            String date = tblTransactionRecord.getValueAt(rowcount, 3).toString();
            Date = date;

            System.out.println("Selected PaymentID: "+PaymentID);
            System.out.println("Selected OrderID: "+OrderID);
            System.out.println("Selected Date: "+Date);
            frmCustViewReceipt recp = new frmCustViewReceipt(UserID,Username,Password,UserRole,Date,PaymentID,OrderID);
            recp.setVisible(true);
            this.dispose();
            logger.info(UserRole + ": " + Username + " " + "will be Viewing the Selected Receipt");
        }else{
            JOptionPane.showMessageDialog(null, "Please Select A Payment To View Receipt!","View Receipt Error",JOptionPane.ERROR_MESSAGE);
            logger.error(UserRole + ": " + Username + " " + "failed to View Receipt (Payment Not Selected)");
        }
        
    }//GEN-LAST:event_btnViewReceiptActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tblTransactionRecord.getModel();
        model.setRowCount(0);
        
        
        try{
            File file = new File("D:\\Documents\\Uni_Modules\\Object Oriented Development with Java\\Group Assignment\\Group_9_APU_Cafeteria_Food_Ordering_System\\src\\main\\java\\Database\\payment.txt");
            Scanner scan = new Scanner(file);
            scan.useDelimiter("[|\n]");
            
            FileReader fr = new FileReader(file);
            
            while(scan.hasNext()){
                
                String paymentidx = scan.next();
                String orderidx = scan.next();
                String useridx = scan.next();
                String usernamex = scan.next();
                String totalamountx = scan.next();
                String datex = scan.next().trim();
                
                if(useridx.equals(UserID)&&usernamex.equals(Username)){
                    System.out.println("------------------------------");
                    System.out.println("Payment ID: "+paymentidx);
                    System.out.println("Order ID: "+orderidx);
                    System.out.println("Customer ID: "+useridx);
                    System.out.println("Username: "+usernamex);
                    System.out.println("Total Amount: "+totalamountx);
                    System.out.println("Date: "+datex);
                    System.out.println("------------------------------");
                    
                    model.addRow(new Object[] {paymentidx,orderidx,"RM "+totalamountx,datex});
                }else{
                    
                }
            }
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(frmCustTransactionRecord.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("File Not Found");
        }
        
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCustTransactionRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCustTransactionRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCustTransactionRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCustTransactionRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCustTransactionRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnViewReceipt;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCategoryName;
    private javax.swing.JPanel pnlBackground;
    public static javax.swing.JTable tblTransactionRecord;
    // End of variables declaration//GEN-END:variables
}
