/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forms.Customer;

import forms.Login.frmLogin;
import java.util.HashSet;
import org.apache.logging.log4j.LogManager;

/**
 *
 * @author User
 */
public class frmCustMainMenu extends javax.swing.JFrame {
//    Variables
    private static String Username;
    private static String Password;
    private static String UserID;
    private static String UserRole;
    
    private static final org.apache.logging.log4j.Logger logger = LogManager.getLogger(frmCustMainMenu.class);
    
    /**
     * Creates new form frmMainMenu
     */
    public frmCustMainMenu() {
        initComponents();
    }
    public frmCustMainMenu(String ID, String u, String p, String r){
        Username = u;
        Password = p;
        UserID = ID;
        UserRole = r;
        initComponents();
    }
    
    public frmCustMainMenu(String ID, String u, String p){
        Username = u;
        Password = p;
        UserID = ID;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblWelcomeCustomer = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        btnTransaction = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");
        setResizable(false);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        pnlBackground.setBackground(new java.awt.Color(51, 51, 51));
        pnlBackground.setPreferredSize(new java.awt.Dimension(450, 700));
        pnlBackground.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblWelcomeCustomer.setBackground(new java.awt.Color(71, 71, 71));
        lblWelcomeCustomer.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblWelcomeCustomer.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcomeCustomer.setText("Welcome, Customer");
        pnlBackground.add(lblWelcomeCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 28, 390, 53));

        btnLogOut.setBackground(new java.awt.Color(102, 102, 102));
        btnLogOut.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setText("LOG OUT");
        btnLogOut.setToolTipText("");
        btnLogOut.setBorder(null);
        btnLogOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogOut.setDefaultCapable(false);
        btnLogOut.setFocusPainted(false);
        btnLogOut.setName(""); // NOI18N
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        pnlBackground.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 203, 46));

        btnTransaction.setBackground(new java.awt.Color(102, 102, 102));
        btnTransaction.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnTransaction.setForeground(new java.awt.Color(255, 255, 255));
        btnTransaction.setText("TRANSACTION HISTORY");
        btnTransaction.setToolTipText("");
        btnTransaction.setBorder(null);
        btnTransaction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTransaction.setDefaultCapable(false);
        btnTransaction.setFocusPainted(false);
        btnTransaction.setName(""); // NOI18N
        btnTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransactionActionPerformed(evt);
            }
        });
        pnlBackground.add(btnTransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, 203, 46));

        btnMenu.setBackground(new java.awt.Color(102, 102, 102));
        btnMenu.setFont(new java.awt.Font("Segoe UI Light", 0, 14)); // NOI18N
        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setText("MENU");
        btnMenu.setToolTipText("");
        btnMenu.setBorder(null);
        btnMenu.setBorderPainted(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.setDefaultCapable(false);
        btnMenu.setFocusPainted(false);
        btnMenu.setName(""); // NOI18N
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        pnlBackground.add(btnMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 238, 203, 46));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        this.toBack();
        this.setVisible(false);
        frmLogin loginform = new frmLogin(UserID,Username,Password);
        loginform.setVisible(true);
        logger.info(UserRole + ": " + Username + " " + "has logged out");
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        this.toBack();
        this.setVisible(false);
        frmCustOrderingMenu custOrderingMenu = new frmCustOrderingMenu(UserID,Username,Password,UserRole);
        custOrderingMenu.setVisible(true);
        custOrderingMenu.toFront();
        this.dispose();
        logger.info(UserRole + ": " + Username + " " + "selected Menu");
    }//GEN-LAST:event_btnMenuActionPerformed

    private void btnTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransactionActionPerformed
        // TODO add your handling code here:
        this.toBack();
        this.setVisible(false);
        frmCustTransactionRecord custTransaction = new frmCustTransactionRecord(UserID,Username,Password,UserRole);
        custTransaction.setVisible(true);
        custTransaction.toFront();
        this.dispose();
        logger.info(UserRole + ": " + Username + " " + "selected Transaction History");
    }//GEN-LAST:event_btnTransactionActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        lblWelcomeCustomer.setText("Welcome, "+Username+".");
    }//GEN-LAST:event_formComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCustMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCustMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCustMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCustMainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCustMainMenu().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnTransaction;
    private static javax.swing.JLabel lblWelcomeCustomer;
    private javax.swing.JPanel pnlBackground;
    // End of variables declaration//GEN-END:variables
}
